O = Point(0, 0)
A = Point(1, 0)
B = Point(0, 1)
x_axis = Line(O, A)
y_axis = Line(O, B)
circle = Circle(O, A)
P = Rotate(A, pi/3, O)
cos_line = PerpendicularLine(P, x_axis)
sin_line = PerpendicularLine(P, y_axis)
cos_foot = Intersect(cos_line, x_axis)
sin_foot = Intersect(sin_line, y_axis)
cos_seg = Segment(O, cos_foot)
sin_seg = Segment(O, sin_foot)
cos_projection = Segment(P, cos_foot)
sin_projection = Segment(P, sin_foot)
OP = Segment(O, P)
style(circle, stroke="color.main", stroke_width_px="line_width.main")
style(x_axis, y_axis, stroke="color.aux", stroke_width_px="line_width.aux")
style(O, label_visible=True, fill="color.main", size_px="point_size.main")
style(A, label_visible=True, fill="color.main", size_px="point_size.main")
style(B, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(P, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(cos_foot, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(sin_foot, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(cos_seg, stroke="color.accent", stroke_width_px="line_width.bold")
style(sin_seg, stroke="color.accent", stroke_width_px="line_width.bold")
style(cos_projection, sin_projection, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="4 2")
style(OP, stroke="color.aux", stroke_width_px="line_width.aux")
style(cos_seg, label_visible=True, label_text="$\\cos\\theta$")
style(sin_seg, label_visible=True, label_text="$\\sin\\theta$")

right_cos = Angle(A, cos_foot, P)
right_sin = Angle(B, sin_foot, P)
style(right_cos, right_sin, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(cos_line, sin_line)
