A = Point(0, 0)
B = Point(4, 1)
AB = Line(A, B)
P = Point(1, 3)
perp_line = PerpendicularLine(P, AB)
H = Intersect(perp_line, AB)
PH = Segment(P, H)
right_angle = Angle(A, H, P)
style(A, B, P, H, label_visible=True)
style(AB, stroke="color.main", stroke_width_px="line_width.main")
style(perp_line, stroke="color.aux", stroke_width_px="line_width.aux")
style(PH, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(perp_line)
