O = Point(0, 0)
A = Point(2, 0)
B = Rotate(A, 2 * pi / 3, O)
circle = Circle(O, A)
sector = CircleSector(O, A, B)
arc_AB = CircleArc(O, A, B)
chord_AB = Segment(A, B)
style(sector, stroke="color.main", stroke_width_px="line_width.main", fill="color.aux")
style(arc_AB, stroke="color.accent", stroke_width_px="line_width.bold")
style(chord_AB, stroke="color.accent", stroke_width_px="line_width.bold")
style(O, A, B, label_visible=True, fill="color.main", size_px="point_size.main")
hide(circle)
