A = Point(0, 0)
B = Point(4, 0)
C = Point(2, 3)
AB = Segment(A, B)
AC = Segment(A, C)
BC = Segment(B, C)
style(AB, AC, BC, stroke="color.main", stroke_width_px="line_width.main")
style(A, B, C, label_visible=True)
ang_B = Angle(A, B, C)
ang_C = Angle(B, C, A)
style(ang_B, ang_C, tick_count=1, arc_size_px="angle_radius.main")
