O = Point(0, 0)
A = Point(2, 1)
circle = Circle(O, Point(3, 0))
A_prime = Reflect(A, circle)
OA = Segment(O, A)
OA_prime = Segment(O, A_prime)
style(O, label_visible=True, fill="color.main", size_px="point_size.main")
style(A, label_visible=True, fill="color.main", size_px="point_size.main")
style(A_prime, label_visible=True, fill="color.accent", size_px="point_size.bold", label_text="$A'$")
style(circle, stroke="color.main", stroke_width_px="line_width.main")
style(OA, OA_prime, stroke="color.aux", stroke_width_px="line_width.aux")
