F1 = Point(-2, 0)
F2 = Point(2, 0)
ellipse = Ellipse(F1, F2, 3)
minor_axis = MinorAxis(ellipse)
P, P_aux = Intersect(ellipse, minor_axis)
PF1 = Segment(P, F1)
PF2 = Segment(P, F2)
style(F1, F2, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(P, label_visible=True, label_text="$P$", fill="color.accent", size_px="point_size.bold")
style(P_aux, label_visible=False, size_px="point_size.aux")
style(PF1, PF2, stroke="color.accent", stroke_width_px="line_width.bold")
style(ellipse, stroke="color.main", stroke_width_px="line_width.main")
style(minor_axis, stroke="color.aux", stroke_width_px="line_width.aux")
