A = Point(-3, 0)
B = Point(3, 0)
P = Point(1, 2)
AB = Line(A, B)
parallel_line = PerpendicularLine(P, PerpendicularLine(P, AB))
style(AB, stroke="color.main", stroke_width_px="line_width.main")
style(parallel_line, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, P, label_visible=True)
style(parallel_line, label_visible=True, label_text="$l$")
