A = Point(-3, -2)
B = Point(4, -1)
C = Point(0, 3)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
style(A, B, C, label_visible=True)
style(AB, BC, CA, stroke="color.main", stroke_width_px="line_width.main")
angA = Angle(B, A, C)
angB = Angle(C, B, A)
angC = Angle(A, C, B)
style(angA, arc_size_px="angle_radius.main", tick_count=1)
style(angB, arc_size_px="angle_radius.main", tick_count=2)
style(angC, arc_size_px="angle_radius.main", tick_count=3)
