O = Point(0, 0)
A = Point(2, 0)
B = Point(4, 0)
inner = Circle(O, A)
outer = Circle(O, B)
r_in = Segment(O, A)
r_out = Segment(O, B)
style(inner, stroke="color.main", stroke_width_px="line_width.main")
style(outer, stroke="color.main", stroke_width_px="line_width.main")
style(r_in, stroke="color.accent", stroke_width_px="line_width.bold")
style(r_out, stroke="color.accent", stroke_width_px="line_width.bold")
style(O, label_visible=True, fill="color.strong", size_px="point_size.bold")
style(A, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(B, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(r_in, label_visible=True, label_text="$r_{in}$")
style(r_out, label_visible=True, label_text="$r_{out}$")
