A = Point(0, 0)
B = Point(4, 0)
C = Point(1, 3)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
style(AB, CA, stroke="color.main", stroke_width_px="line_width.main")
style(BC, stroke="color.accent", stroke_width_px="line_width.bold")
bis_line = AngularBisector(B, A, C)
D = Intersect(bis_line, BC)
AD = Segment(A, D)
style(AD, stroke="color.accent", stroke_width_px="line_width.bold")
ang1 = Angle(B, A, D)
ang2 = Angle(D, A, C)
style(ang1, ang2, arc_size_px="angle_radius.main", tick_count=1)
hide(bis_line)
style(A, B, C, D, label_visible=True)
style(D, fill="color.accent", size_px="point_size.bold")
