O = Point(0, 0)
A = Point(-2.1, 1.7)
B = Point(2.1, 1.7)
C = Point(-2.1, -1.7)
D = Point(2.1, -1.7)
circle = Circle(O, A)
chord1 = Segment(A, B)
chord2 = Segment(C, D)
E = Intersect(chord1, chord2)
style(circle, stroke="color.main", stroke_width_px="line_width.main")
style(chord1, chord2, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, C, D, E, label_visible=True, fill="color.main", size_px="point_size.main")
style(E, fill="color.accent", size_px="point_size.bold")
