F = Point(0, 1)
d = Line(Point(-3, -1), Point(3, -1))
parabola = Parabola(F, d)
vertex = Center(parabola)
axis = Axes(parabola)
style(parabola, stroke="color.main", stroke_width_px="line_width.main")
style(F, label_visible=True, fill="color.strong", size_px="point_size.bold")
style(d, stroke="color.aux", stroke_width_px="line_width.aux")
style(vertex, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(axis, stroke="color.accent", stroke_width_px="line_width.bold")
hide(d)
