F1 = Point(-2, 0)
F2 = Point(2, 0)
hyperbola = Hyperbola(F1, F2, 1.2)
center = Center(hyperbola)
V1, V2 = Vertex(hyperbola)
major_axis = MajorAxis(hyperbola)
minor_axis = MinorAxis(hyperbola)
style(F1, F2, fill="color.strong", size_px="point_size.bold", label_visible=True)
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(center, fill="color.accent", size_px="point_size.bold", label_visible=True)
style(V1, V2, fill="color.accent", size_px="point_size.bold", label_visible=True)
style(major_axis, stroke="color.accent", stroke_width_px="line_width.bold")
style(minor_axis, stroke="color.aux", stroke_width_px="line_width.aux")
style(hyperbola, stroke="color.main", stroke_width_px="line_width.main")
