O = Point(0, 0)
A = Point(-2.1, 1.7)
B = Point(2.1, 1.7)
circle = Circle(O, A)
C = Point(-1.5, -2.3)
OA = Segment(O, A)
OB = Segment(O, B)
CA = Segment(C, A)
CB = Segment(C, B)
arc_AB = CircleArc(O, B, A)
style(O, A, B, C, label_visible=True)
style(OA, OB, stroke="color.main", stroke_width_px="line_width.main")
style(CA, CB, stroke="color.accent", stroke_width_px="line_width.bold")
style(circle, stroke="color.aux", stroke_width_px="line_width.aux")
style(arc_AB, stroke="color.aux", stroke_width_px="line_width.aux")
