O = Point(0, 0)
A = Point(2, 0)
B = Rotate(A, 2 * pi / 3, O)
C = Rotate(A, pi / 2, O)
circle = Circle(O, A)
OA = Segment(O, A)
OB = Segment(O, B)
CA = Segment(C, A)
CB = Segment(C, B)
central = Angle(A, O, B)
inscribed = Angle(A, C, B)
style(circle, stroke="color.main", stroke_width_px="line_width.main")
style(OA, OB, CA, CB, stroke="color.main", stroke_width_px="line_width.main")
style(O, A, B, C, fill="color.main", size_px="point_size.main", label_visible=True)
style(central, arc_size_px="angle_radius.bold", tick_count=2, label_visible=True, label_text="$2\\alpha$")
style(inscribed, arc_size_px="angle_radius.bold", tick_count=1, label_visible=True, label_text="$\\alpha$")
hide(OA, OB, CA, CB)
