A = Point(-3, 0)
B = Point(3, 0)
O = Midpoint(A, B)
semi = Semicircle(A, B)
C = Rotate(B, pi/3, O)
AC = Segment(A, C)
BC = Segment(B, C)
right_angle = Angle(A, C, B)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(A, B, C, label_visible=True)
style(O, label_visible=False)
style(AC, BC, stroke="color.main", stroke_width_px="line_width.main")
style(semi, stroke="color.main", stroke_width_px="line_width.main")
