F1 = Point(-2, 0)
F2 = Point(2, 0)
ellipse = Ellipse(F1, F2, 3)
center = Center(ellipse)
major_axis = MajorAxis(ellipse)
minor_axis = MinorAxis(ellipse)
style(ellipse, stroke="color.main", stroke_width_px="line_width.main")
style(center, fill="color.accent", size_px="point_size.bold", label_visible=True, label_text="$O$")
style(major_axis, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="4 2")
style(minor_axis, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="4 2")
style(F1, F2, fill="color.strong", size_px="point_size.bold", label_visible=True, label_text="$F_1$", label_text="$F_2$")
