O = Point(0, 0)
A = Point(3, 0)
circle = Circle(O, A)
hexagon, AB, BC, CD, DE, EF, FA, B, C, D, E, F = Polygon(A, A, 6)
style(O, label_visible=True, fill="color.main", size_px="point_size.main")
style(A, B, C, D, E, F, label_visible=True, fill="color.main", size_px="point_size.main")
style(circle, stroke="color.aux", stroke_width_px="line_width.aux")
style(hexagon, stroke="color.main", stroke_width_px="line_width.main")
style(AB, BC, CD, DE, EF, FA, stroke="color.main", stroke_width_px="line_width.main")
