"""Auto-generated IDE stubs for scene10.ggb.

Do not edit — regenerated by loadGGB on each call.
Source: scene10.ggb
"""

from animageo.dsl import *  # noqa: F401,F403

# ── Angle ──
α: Angle
β: Angle
γ: Angle

# ── Circle ──
d: Circle
q: Circle

# ── Line ──
f: Line
g: Line
h: Line
l: Line
xAxis: Line
yAxis: Line

# ── Point ──
A: Point
B: Point
C: Point
D: Point
E: Point
J_1: Point
K: Point
M: Point
Q: Point
R: Point

# ── Polygon ──
t1: Polygon

# ── Segment ──
a: Segment
b: Segment
c: Segment
i: Segment
j: Segment
k: Segment
m: Segment
