O = Point(0, 0)
c = Circle(O, 2)
P = Point(4.2, 1.6)

t1, t2 = Tangent(P, c)
T1 = Intersect(c, t1)
T2 = Intersect(c, t2)
tangent_1 = Segment(P, T1)
tangent_2 = Segment(P, T2)
r1 = Segment(O, T1)
r2 = Segment(O, T2)
right_1 = Angle(O, T1, P)
right_2 = Angle(O, T2, P)

hide(t1, t2)
style(O, P, T1, T2, label_visible=True)
style(T1, label_text="$T_1$")
style(T2, label_text="$T_2$")
style(tangent_1, tangent_2, stroke="color.accent", stroke_width_px="line_width.bold")
style(r1, r2, stroke="color.aux", stroke_width_px="line_width.main")
style(right_1, right_2, right_angle_marker=True)
