A = Point(-3.2, -1.6)
B = Point(3.2, -1.2)
C = Point(-0.4, 2.6)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
median_A = Segment(A, M_bc)
median_C = Segment(C, M_ab)
G = Intersect(median_A, median_C)
circum = Circle(A, B, C)
O = Center(circum)
line_AB = Line(A, B)
line_BC = Line(B, C)
alt_C = PerpendicularLine(C, line_AB)
alt_A = PerpendicularLine(A, line_BC)
H = Intersect(alt_A, alt_C)
euler = Line(O, H)

hide(line_AB, line_BC, alt_A, alt_C)
style(A, B, C, G, O, H, label_visible=True)
style(circum, stroke="color.aux", stroke_width_px="line_width.main")
style(median_A, median_C, stroke="color.aux", stroke_width_px="line_width.aux")
style(euler, stroke="color.accent", stroke_width_px="line_width.bold")
