A = Point(-1, 3)
B = Point(-4, -2)
C = Point(4, -2)
tri, AB, BC, CA = Polygon(A, B, C)
bis_line = AngularBisector(B, A, C)
D = Intersect(bis_line, BC)
AD = Segment(A, D)
BD = Segment(B, D)
DC = Segment(D, C)
angle1 = Angle(B, A, D)
angle2 = Angle(D, A, C)
hide(bis_line)
style(AD, stroke="color.accent", stroke_width_px="line_width.bold")
style(BD, DC, stroke="color.accent", stroke_width_px="line_width.bold")
style(angle1, tick_count=1, arc_size_px=22)
style(angle2, tick_count=1, arc_size_px=28)
