F1 = Point(-2.0, 0)
F2 = Point(2.0, 0)
hyp = Hyperbola(F1, F2, 1.2)
O = Center(hyp)
V1, V2 = Vertex(hyp)
major = MajorAxis(hyp)
minor = MinorAxis(hyp)

style(F1, F2, O, V1, V2, label_visible=True)
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(V1, label_text="$V_1$")
style(V2, label_text="$V_2$")
style(hyp, stroke="color.accent", stroke_width_px="line_width.bold")
style(major, minor, stroke="color.aux", stroke_width_px="line_width.main")
style(V1, V2, fill="color.accent", size_px="point_size.bold")
