A = Point(0, 0)
B = Point(4, 0)
C = Point(1, 3)
P = Point(2, -2)
Q = Point(5, -2)
ray_AB = Ray(A, B)
ray_AC = Ray(A, C)
angle_BAC = Angle(B, A, C)
style(angle_BAC, arc_size_px=20)
ray_PQ = Ray(P, Q)
R = Rotate(Q, angle_BAC, P)
ray_PR = Ray(P, R)
angle_QPR = Angle(Q, P, R)
style(angle_QPR, arc_size_px=20, stroke="color.accent")
style(A, B, C, P, Q, R, label_visible=True)
