O = Point(0, 0)
A = Point(2.6, 0)
c = Circle(O, A)
B = Rotate(A, 1.55, O)
C = Rotate(A, 3.35, O)
D = Rotate(A, 5.25, O)
quad, AB, BC, CD, DA = Polygon(A, B, C, D)
angle_A = Angle(D, A, B)
angle_C = Angle(B, C, D)

hide(O)
style(A, B, C, D, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(angle_A, label_visible=True, label_text="$\\alpha$", arc_size_px=24)
style(angle_C, label_visible=True, label_text="$180^\\circ-\\alpha$", arc_size_px=24)
style(AB, BC, CD, DA, stroke="color.strong", stroke_width_px="line_width.main")
