O = Point(0, 0)
A = Point(3, 0)
angle = 2 * pi / 3
B = Rotate(A, angle, O)
c = Circle(O, A)
arc = CircularArc(O, A, B)
radius_OA = Segment(O, A)
radius_OB = Segment(O, B)
center_angle = Angle(A, O, B)
style(O, A, B, label_visible=True)
style(radius_OA, radius_OB, stroke="color.accent", stroke_width_px="line_width.bold")
style(center_angle, stroke="color.accent")
style(c, stroke="color.aux", stroke_width_px=0.5, stroke_opacity=0.5)
style(arc, stroke="color.main", stroke_width_px="line_width.main")
