A = Point(-3.4, -1.6)
B = Point(3.2, -1.4)
C = Point(-0.3, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
M_ca = Midpoint(C, A)
medial, s1, s2, s3 = Polygon(M_ab, M_bc, M_ca)
AB_l = Segment(A, M_ab)
AB_r = Segment(M_ab, B)
BC_l = Segment(B, M_bc)
BC_r = Segment(M_bc, C)
CA_l = Segment(C, M_ca)
CA_r = Segment(M_ca, A)

style(A, B, C, M_ab, M_bc, M_ca, label_visible=True)
style(M_ab, label_text="$M_{AB}$")
style(M_bc, label_text="$M_{BC}$")
style(M_ca, label_text="$M_{CA}$")
style(medial, fill="color.accent", fill_opacity=0.12)
style(s1, s2, s3, stroke="color.accent", stroke_width_px="line_width.bold")
style(AB_l, AB_r, stroke_width_px=0, tick_count=1)
style(BC_l, BC_r, stroke_width_px=0, tick_count=2)
style(CA_l, CA_r, stroke_width_px=0, tick_count=3)
