A = Point(0, 2.4)
C = Point(0, -2.0)
B = Point(2.2, -0.25)
axis = Line(A, C)
D = Reflect(B, axis)
kite, AB, BC, CD, DA = Polygon(A, B, C, D)
diag_AC = Segment(A, C)
diag_BD = Segment(B, D)
O = Intersect(diag_AC, diag_BD)
right_O = Angle(B, O, C)

hide(axis)
style(A, B, C, D, O, label_visible=True)
style(AB, DA, tick_count=1)
style(BC, CD, tick_count=2)
style(diag_AC, stroke="color.accent", stroke_width_px="line_width.bold")
style(diag_BD, stroke="color.aux", stroke_width_px="line_width.main")
style(right_O, right_angle_marker=True)
