A = Point(0, 0)
B = Point(3, 0)
C = A + (B - A) * (2 / 3)
D = B + (B - A)
M = Midpoint(C, D)
apollonius_circle = Circle(M, C)
style(A, B, label_visible=True, size_px="point_size.main")
style(apollonius_circle, stroke="color.accent", stroke_width_px="line_width.bold")
hide(C, D, M)
