A = Point(-3.2, -1.7)
B = Point(3.2, -1.2)
C = Point(-0.6, 2.6)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
median_A = Segment(A, M_bc)
median_C = Segment(C, M_ab)
G = Intersect(median_A, median_C)
K = IsogonalConjugation(A, B, C, G)
sym_A = Segment(A, K)
sym_B = Segment(B, K)
sym_C = Segment(C, K)

style(A, B, C, G, K, label_visible=True)
style(K, fill="color.accent", size_px="point_size.bold")
style(sym_A, sym_B, sym_C, stroke="color.accent", stroke_width_px="line_width.bold")
style(median_A, median_C, stroke="color.aux", stroke_width_px="line_width.aux")
