A = Point(2.2, 0)
B = Point(1.1, 1.905)
hexagon, AB, BC, CD, DE, EF, FA, C, D, E, F = Polygon(A, B, 6)
O = Point(0, 0)
circle = Circle(O, A)
OA = Segment(O, A)
OB = Segment(O, B)
OC = Segment(O, C)
OD = Segment(O, D)
OE = Segment(O, E)
OF = Segment(O, F)

style(A, B, C, D, E, F, O, label_visible=True)
style(circle, stroke="color.aux", stroke_width_px="line_width.main")
style(AB, BC, CD, DE, EF, FA, tick_count=1)
style(OA, OB, OC, OD, OE, OF, stroke="color.accent", stroke_width_px="line_width.main")
