O = Point(0, 0)
c = Circle(O, 1.8)
P = Point(4.1, 0.8)
sec_line = Line(P, O)
A, B = Intersect(c, sec_line)
t1, t2 = Tangent(P, c)
T = Intersect(c, t1)
PT = Segment(P, T)
PA = Segment(P, A)
PB = Segment(P, B)
OT = Segment(O, T)
right_T = Angle(O, T, P)

hide(sec_line, t1, t2)
style(O, P, A, B, T, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(PT, stroke="color.accent", stroke_width_px="line_width.bold", label_visible=True, label_text="$PT^2=PA\\cdot PB$")
style(PA, PB, stroke="color.strong", stroke_width_px="line_width.main")
style(OT, stroke="color.aux", stroke_width_px="line_width.main")
style(right_T, right_angle_marker=True)
