A = Point(-3.1, -1.6)
B = Point(3.0, -1.3)
C = Point(-0.5, 2.3)
tri, AB, BC, CA = Polygon(A, B, C)
inc = Incircle(A, B, C)
I = Center(inc)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
p_ab = PerpendicularLine(I, line_AB)
p_bc = PerpendicularLine(I, line_BC)
p_ca = PerpendicularLine(I, line_CA)
T_ab = Intersect(line_AB, p_ab)
T_bc = Intersect(line_BC, p_bc)
T_ca = Intersect(line_CA, p_ca)
r_ab = Segment(I, T_ab)
r_bc = Segment(I, T_bc)
r_ca = Segment(I, T_ca)
right_ab = Angle(A, T_ab, I)
right_bc = Angle(B, T_bc, I)
right_ca = Angle(C, T_ca, I)

hide(line_AB, line_BC, line_CA, p_ab, p_bc, p_ca)
style(A, B, C, I, T_ab, T_bc, T_ca, label_visible=True)
style(T_ab, label_text="$T_{AB}$")
style(T_bc, label_text="$T_{BC}$")
style(T_ca, label_text="$T_{CA}$")
style(inc, stroke="color.accent", stroke_width_px="line_width.bold")
style(r_ab, r_bc, r_ca, stroke="color.aux", stroke_width_px="line_width.main")
style(right_ab, right_bc, right_ca, right_angle_marker=True)
