A = Point(-2.8, -1.5)
B = Point(2.6, -1.3)
C = Point(-0.4, 2.2)
tri, AB, BC, CA = Polygon(A, B, C)
D = Rotate(C, -pi / 3, B)
E = Rotate(A, -pi / 3, C)
F = Rotate(B, -pi / 3, A)
eq_BC, BC_1, CD, DB = Polygon(B, C, D)
eq_CA, CA_1, AE, EC = Polygon(C, A, E)
eq_AB, AB_1, BF, FA = Polygon(A, B, F)
line_AD = Segment(A, D)
line_BE = Segment(B, E)
line_CF = Segment(C, F)
X = Intersect(line_AD, line_BE)

style(A, B, C, D, E, F, X, label_visible=True)
style(X, label_text="$F_1$", fill="color.accent", size_px="point_size.bold")
style(eq_BC, eq_CA, eq_AB, fill="color.accent", fill_opacity=0.08)
style(line_AD, line_BE, line_CF, stroke="color.accent", stroke_width_px="line_width.bold")
