A = Point(-3.2, -1.0)
B = Point(3.0, -0.4)
P = Point(-0.8, 2.0)
base = Line(A, B)
perp = PerpendicularLine(P, base)
H = Intersect(base, perp)
PH = Segment(P, H)
right_H = Angle(A, H, P)

hide(perp)
style(A, B, P, H, label_visible=True)
style(base, stroke="color.strong", stroke_width_px="line_width.main")
style(PH, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_H, right_angle_marker=True)
