A = Point(-3, 0)
B = Point(3, 0)
C = Point(0, 4)
ABseg = Segment(A, B)
BCseg = Segment(B, C)
CAseg = Segment(C, A)
ABline = Line(A, B)
BCline = Line(B, C)
CAline = Line(C, A)
midAB = Midpoint(A, B)
midBC = Midpoint(B, C)
perpAB = PerpendicularBisector(A, B)
perpBC = PerpendicularBisector(B, C)
O = Intersect(perpAB, perpBC)
circ = Circle(O, A)
P = Rotate(A, 1.2, O)
perpP_AB = PerpendicularLine(P, ABline)
perpP_BC = PerpendicularLine(P, BCline)
perpP_CA = PerpendicularLine(P, CAline)
footAB = Intersect(ABline, perpP_AB)
footBC = Intersect(BCline, perpP_BC)
footCA = Intersect(CAline, perpP_CA)
segP_footAB = Segment(P, footAB)
segP_footBC = Segment(P, footBC)
segP_footCA = Segment(P, footCA)
simson = Line(footAB, footBC)
right_AB = Angle(A, footAB, P)
right_BC = Angle(B, footBC, P)
right_CA = Angle(C, footCA, P)
style(A, B, C, label_visible=True)
style(O, label_visible=True, label_text="$O$")
style(P, label_visible=True, label_text="$P$")
style(footAB, footBC, footCA, label_visible=True, size_px="point_size.aux")
style(simson, stroke="color.accent", stroke_width_px="line_width.bold")
style(segP_footAB, segP_footBC, segP_footCA, stroke="color.aux", stroke_width_px="line_width.aux", line_dash="dashed")
style(right_AB, right_BC, right_CA, right_angle_marker=True)
hide(perpP_AB, perpP_BC, perpP_CA)
hide(perpAB, perpBC)
style(ABline, BCline, CAline, stroke="color.aux", stroke_width_px="line_width.aux", line_dash="dotted")
