O = Point(0, 0)
A = Point(1, 0)
B = Point(0, 1)
x_axis = Line(O, A)
y_axis = Line(O, B)
c = Circle(O, 1)
P = Rotate(A, 1.0471975511965976, O)  # angle = pi/3
foot_x = Intersect(PerpendicularLine(P, x_axis), x_axis)
foot_y = Intersect(PerpendicularLine(P, y_axis), y_axis)
seg_cos = Segment(P, foot_x)
seg_sin = Segment(P, foot_y)
style(O, label_visible=True, label_text="$O$")
style(A, label_visible=True, label_text="$A$")
style(B, label_visible=True, label_text="$B$")
style(x_axis, label_visible=True, label_text="$x$")
style(y_axis, label_visible=True, label_text="$y$")
style(P, label_visible=True, label_text="$P$")
style(foot_x, label_visible=True, label_text="$P_x$")
style(foot_y, label_visible=True, label_text="$P_y$")
style(seg_cos, stroke="color.accent", stroke_width_px="line_width.bold")
style(seg_sin, stroke="color.accent", stroke_width_px="line_width.bold")
