A = Point(-3.3, -1.5)
B = Point(3.1, -1.2)
C = Point(-0.8, 2.6)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
M_ca = Midpoint(C, A)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
alt_A_line = PerpendicularLine(A, line_BC)
alt_B_line = PerpendicularLine(B, line_CA)
alt_C_line = PerpendicularLine(C, line_AB)
H = Intersect(alt_A_line, alt_B_line)
F_a = Intersect(line_BC, alt_A_line)
F_b = Intersect(line_CA, alt_B_line)
F_c = Intersect(line_AB, alt_C_line)
E_a = Midpoint(A, H)
E_b = Midpoint(B, H)
E_c = Midpoint(C, H)
nine = Circle(M_ab, M_bc, M_ca)
alt_A = Segment(A, F_a)
alt_B = Segment(B, F_b)
alt_C = Segment(C, F_c)

hide(line_AB, line_BC, line_CA, alt_A_line, alt_B_line, alt_C_line)
style(A, B, C, H, label_visible=True)
style(M_ab, M_bc, M_ca, F_a, F_b, F_c, E_a, E_b, E_c, label_visible=False, size_px="point_size.aux")
style(nine, stroke="color.accent", stroke_width_px="line_width.bold")
style(alt_A, alt_B, alt_C, stroke="color.aux", stroke_width_px="line_width.aux")
