A = Point(-2.6, -0.6)
B = Point(2.6, -0.6)
AB = Segment(A, B)
cA = Circle(A, B)
cB = Circle(B, A)
P, Q = Intersect(cA, cB)
bisector = Line(P, Q)
M = Intersect(AB, bisector)
AM = Segment(A, M)
MB = Segment(M, B)
right_M = Angle(A, M, P)

style(A, B, M, P, Q, label_visible=True)
style(cA, cB, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
style(bisector, stroke="color.accent", stroke_width_px="line_width.bold")
style(AM, MB, stroke_width_px=0, tick_count=1)
style(right_M, right_angle_marker=True)
