A = Point(-2.9, -1.4)
B = Point(2.7, -1.2)
C = Point(-0.4, 2.3)
tri, AB, BC, CA = Polygon(A, B, C)
D = Rotate(C, -pi / 3, B)
E = Rotate(A, -pi / 3, C)
F = Rotate(B, -pi / 3, A)
eq_BC, s1, s2, s3 = Polygon(B, C, D)
eq_CA, s4, s5, s6 = Polygon(C, A, E)
eq_AB, s7, s8, s9 = Polygon(A, B, F)
N_a = Centroid(eq_BC)
N_b = Centroid(eq_CA)
N_c = Centroid(eq_AB)
napoleon, n1, n2, n3 = Polygon(N_a, N_b, N_c)

style(A, B, C, D, E, F, N_a, N_b, N_c, label_visible=True)
style(N_a, label_text="$N_a$")
style(N_b, label_text="$N_b$")
style(N_c, label_text="$N_c$")
style(eq_BC, eq_CA, eq_AB, fill="color.aux", fill_opacity=0.08)
style(napoleon, fill="color.accent", fill_opacity=0.16)
style(n1, n2, n3, stroke="color.accent", stroke_width_px="line_width.bold")
