O1 = Point(-1.2, 0)
O2 = Point(1.2, 0)
c1 = Circle(O1, 2.2)
c2 = Circle(O2, 2.2)
P, Q = Intersect(c1, c2)
chord = Segment(P, Q)
arc1 = CircleArc(O1, Q, P)
arc2 = CircleArc(O2, P, Q)
centers = Segment(O1, O2)

style(O1, O2, P, Q, label_visible=True)
style(O1, label_text="$O_1$")
style(O2, label_text="$O_2$")
style(c1, c2, stroke="color.aux", stroke_width_px="line_width.main")
style(chord, stroke="color.strong", stroke_width_px="line_width.main")
style(arc1, arc2, stroke="color.accent", stroke_width_px="line_width.bold")
style(centers, stroke="color.aux", stroke_width_px="line_width.aux")
