A = Point(-3.2, -1.5)
B = Point(3.0, -1.1)
C = Point(-0.7, 2.7)
tri, AB, BC, CA = Polygon(A, B, C)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
alt_A_line = PerpendicularLine(A, line_BC)
alt_B_line = PerpendicularLine(B, line_CA)
alt_C_line = PerpendicularLine(C, line_AB)
H = Intersect(alt_A_line, alt_B_line)
F_a = Intersect(line_BC, alt_A_line)
F_b = Intersect(line_CA, alt_B_line)
F_c = Intersect(line_AB, alt_C_line)
alt_A = Segment(A, F_a)
alt_B = Segment(B, F_b)
alt_C = Segment(C, F_c)
right_A = Angle(B, F_a, A)
right_B = Angle(C, F_b, B)
right_C = Angle(A, F_c, C)

hide(line_AB, line_BC, line_CA, alt_A_line, alt_B_line, alt_C_line)
style(A, B, C, H, F_a, F_b, F_c, label_visible=True)
style(F_a, label_text="$H_a$")
style(F_b, label_text="$H_b$")
style(F_c, label_text="$H_c$")
style(alt_A, alt_B, alt_C, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_A, right_B, right_C, right_angle_marker=True)
