O = Point(0, 0)
A = Point(-2.2, -1.0)
B = Point(-0.3, -1.4)
C = Point(-1.3, 0.8)
tri, AB, BC, CA = Polygon(A, B, C)
A_rot = Rotate(A, pi / 3, O)
B_rot = Rotate(B, pi / 3, O)
C_rot = Rotate(C, pi / 3, O)
tri_rot, A1B1, B1C1, C1A1 = Polygon(A_rot, B_rot, C_rot)
arc_A = CircleArc(O, A, A_rot)
OA = Segment(O, A)
OA1 = Segment(O, A_rot)
angle_A = Angle(A, O, A_rot)

style(O, A, B, C, A_rot, B_rot, C_rot, label_visible=True)
style(A_rot, label_text="$A'$")
style(B_rot, label_text="$B'$")
style(C_rot, label_text="$C'$")
style(tri_rot, fill="color.accent", fill_opacity=0.12)
style(arc_A, stroke="color.accent", stroke_width_px="line_width.bold")
style(OA, OA1, stroke="color.aux", stroke_width_px="line_width.aux")
style(angle_A, label_visible=True, label_text="$60^\\circ$", arc_size_px=30)
