A = Point(-3.0, -1.5)
B = Point(3.1, -1.2)
C = Point(-0.5, 2.5)
P = Point(0.1, 0.1)
tri, AB, BC, CA = Polygon(A, B, C)
line_AP = Line(A, P)
line_BP = Line(B, P)
line_CP = Line(C, P)
D = Intersect(line_AP, BC)
E = Intersect(line_BP, CA)
F = Intersect(line_CP, AB)
cev_A = Segment(A, D)
cev_B = Segment(B, E)
cev_C = Segment(C, F)

hide(line_AP, line_BP, line_CP)
style(A, B, C, P, D, E, F, label_visible=True)
style(P, fill="color.accent", size_px="point_size.bold")
style(cev_A, cev_B, cev_C, stroke="color.accent", stroke_width_px="line_width.bold")
