A = Point(-2.7, -1.8)
B = Point(2.7, -1.8)
C = Point(0, -1.8 + 5.4 * sqrt(3) / 2)
P = Point(-0.2, 0.0)
tri, AB, BC, CA = Polygon(A, B, C)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
p_ab = PerpendicularLine(P, line_AB)
p_bc = PerpendicularLine(P, line_BC)
p_ca = PerpendicularLine(P, line_CA)
F_ab = Intersect(line_AB, p_ab)
F_bc = Intersect(line_BC, p_bc)
F_ca = Intersect(line_CA, p_ca)
d_ab = Segment(P, F_ab)
d_bc = Segment(P, F_bc)
d_ca = Segment(P, F_ca)
right_ab = Angle(A, F_ab, P)
right_bc = Angle(B, F_bc, P)
right_ca = Angle(C, F_ca, P)

hide(line_AB, line_BC, line_CA, p_ab, p_bc, p_ca)
style(A, B, C, P, label_visible=True)
style(F_ab, F_bc, F_ca, label_visible=False, size_px="point_size.aux")
style(d_ab, d_bc, d_ca, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_ab, right_bc, right_ca, right_angle_marker=True)
