O = Point(0, 0)
P = Point(-2.1, 1.7)
Q = Point(2.1, 1.7)
c = Circle(O, P)
chord = Segment(P, Q)
arc_PQ = CircleArc(O, Q, P)

style(O, P, Q, label_visible=True)
style(chord, stroke="color.strong", stroke_width_px="line_width.bold")
style(arc_PQ, stroke="color.accent", stroke_width_px="line_width.bold")
