A = Point(-3.3, -1.8)
B = Point(3.1, -1.4)
C = Point(-0.7, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
inc = Incircle(A, B, C)
I = Center(inc)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
perp_ab = PerpendicularLine(I, line_AB)
perp_bc = PerpendicularLine(I, line_BC)
perp_ca = PerpendicularLine(I, line_CA)
T_ab = Intersect(line_AB, perp_ab)
T_bc = Intersect(line_BC, perp_bc)
T_ca = Intersect(line_CA, perp_ca)
cev_A = Segment(A, T_bc)
cev_B = Segment(B, T_ca)
cev_C = Segment(C, T_ab)
G_e = Intersect(cev_A, cev_B)
r_ab = Segment(I, T_ab)
r_bc = Segment(I, T_bc)
r_ca = Segment(I, T_ca)
right_ab = Angle(A, T_ab, I)
right_bc = Angle(B, T_bc, I)
right_ca = Angle(C, T_ca, I)

hide(line_AB, line_BC, line_CA, perp_ab, perp_bc, perp_ca)
style(A, B, C, I, G_e, T_ab, T_bc, T_ca, label_visible=True)
style(G_e, label_text="$G_e$", fill="color.accent", size_px="point_size.bold")
style(T_ab, label_text="$T_{AB}$")
style(T_bc, label_text="$T_{BC}$")
style(T_ca, label_text="$T_{CA}$")
style(inc, stroke="color.aux", stroke_width_px="line_width.main")
style(cev_A, cev_B, cev_C, stroke="color.accent", stroke_width_px="line_width.bold")
style(r_ab, r_bc, r_ca, stroke="color.aux", stroke_width_px="line_width.aux")
style(right_ab, right_bc, right_ca, right_angle_marker=True)
