A = Point(-2.8, -1.0)
B = Point(2.8, -1.0)
M = Midpoint(A, B)
semicircle = Semicircle(A, B)
C = Rotate(B, 2.1, M)
diameter = Segment(A, B)
AC = Segment(A, C)
BC = Segment(B, C)
angle_C = Angle(A, C, B)

hide(M)
style(A, B, C, label_visible=True)
style(semicircle, stroke="color.accent", stroke_width_px="line_width.bold")
style(diameter, stroke="color.aux", stroke_width_px=2.0)
style(AC, BC, stroke="color.strong", stroke_width_px=2.0)
style(angle_C, right_angle_marker=True)
