A = Point(-2.8, -1.4)
B = Point(-0.4, -0.6)
C = Point(-2.0, 1.4)
L1 = Point(0.7, -2.2)
L2 = Point(1.2, 2.4)
axis = Line(L1, L2)
tri, AB, BC, CA = Polygon(A, B, C)
A_ref = Reflect(A, axis)
B_ref = Reflect(B, axis)
C_ref = Reflect(C, axis)
tri_ref, A1B1, B1C1, C1A1 = Polygon(A_ref, B_ref, C_ref)
a_to_axis = Segment(A, A_ref)
b_to_axis = Segment(B, B_ref)
c_to_axis = Segment(C, C_ref)

hide(L1, L2)
style(A, B, C, A_ref, B_ref, C_ref, label_visible=True)
style(A_ref, label_text="$A'$")
style(B_ref, label_text="$B'$")
style(C_ref, label_text="$C'$")
style(axis, label_visible=True, label_text="$l$", stroke="color.accent", stroke_width_px="line_width.bold")
style(tri_ref, fill="color.accent", fill_opacity=0.12)
style(a_to_axis, b_to_axis, c_to_axis, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
