A = Point(-3.0, -1.6)
B = Point(3.0, -1.6)
D = Point(-1.8, 1.5)
C = D + (B - A) * 0.62
trap, AB, BC, CD, DA = Polygon(A, B, C, D)
M_ad = Midpoint(A, D)
M_bc = Midpoint(B, C)
midline = Segment(M_ad, M_bc)
AD_1 = Segment(A, M_ad)
AD_2 = Segment(M_ad, D)
BC_1 = Segment(B, M_bc)
BC_2 = Segment(M_bc, C)

style(A, B, C, D, M_ad, M_bc, label_visible=True)
style(M_ad, label_text="$M_{AD}$")
style(M_bc, label_text="$M_{BC}$")
style(midline, stroke="color.accent", stroke_width_px="line_width.bold")
style(AD_1, AD_2, stroke_width_px=0, tick_count=1)
style(BC_1, BC_2, stroke_width_px=0, tick_count=2)
