A = Point(-3.0, -1.4)
B = Point(2.8, -1.2)
C = Point(-0.4, 2.2)
tri, AB, BC, CA = Polygon(A, B, C)
D = C + (C - A) * 0.55
ext_side = Segment(C, D)
alpha = Angle(B, A, C)
beta = Angle(C, B, A)
exterior = Angle(B, C, D)

hide(D)
style(A, B, C, label_visible=True)
style(ext_side, stroke="color.accent", stroke_width_px="line_width.bold")
style(alpha, beta, tick_count=1, arc_size_px=22)
style(exterior, label_visible=True, label_text="$\\alpha+\\beta$", arc_size_px=34)
