A = Point(0, 2.2)
B = Point(-2.4, -1.4)
C = Point(2.4, -1.4)
tri, AB, BC, CA = Polygon(A, B, C)
angle_B = Angle(A, B, C)
angle_C = Angle(B, C, A)

style(A, B, C, label_visible=True)
style(AB, CA, tick_count=1)
style(BC, stroke="color.strong", stroke_width_px="line_width.main")
style(angle_B, angle_C, tick_count=1, arc_size_px=24)
