A = Point(0, 0)
B = Point(4, 0)
C = Point(0, 3)
tri = Polygon(A, B, C)
D = Point(4, 4)
E = Point(0, 4)
square_AB = Polygon(A, B, D, E)
F = Point(3, 3)
G = Point(3, 0)
square_AC = Polygon(A, C, F, G)
P = Point(3, 7)
Q = Point(7, 4)
square_BC = Polygon(B, C, P, Q)
ra = Angle(B, A, C)
style(ra, right_angle_marker=True)
style(A, B, C, label_visible=True)
style(square_AB, fill="#aaddaa", opacity=0.3, stroke="#2d2d2d")
style(square_AC, fill="#aaddaa", opacity=0.3, stroke="#2d2d2d")
style(square_BC, fill="#ffaaaa", opacity=0.3, stroke="#2d2d2d")
style(tri, fill="#88aaff", opacity=0.4, stroke="#3b3b3b", stroke_width_px=3)
style(D, E, F, G, P, Q, label_visible=False)
