A = Point(-4, 0)
B = Point(4, 0)
C = Point(1, 3)
tri, AB, BC, CA = Polygon(A, B, C)
base_line = Line(A, B)
alt_line = PerpendicularLine(C, base_line)
H = Intersect(base_line, alt_line)
height_seg = Segment(C, H)
right_angle = Angle(A, H, C)
style(right_angle, right_angle_marker=True)
hide(base_line, alt_line)
style(AB, stroke="color.strong", stroke_width_px="line_width.bold")
style(height_seg, stroke="color.strong", stroke_width_px="line_width.bold")
style(A, B, C, H, label_visible=True)
