A = Point(-3.1, -1.5)
B = Point(3.2, -1.3)
C = Point(-0.4, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
alt_A = PerpendicularLine(A, line_BC)
alt_B = PerpendicularLine(B, line_CA)
alt_C = PerpendicularLine(C, line_AB)
F_a = Intersect(line_BC, alt_A)
F_b = Intersect(line_CA, alt_B)
F_c = Intersect(line_AB, alt_C)
orthic, a1, a2, a3 = Polygon(F_a, F_b, F_c)
AF_a = Segment(A, F_a)
BF_b = Segment(B, F_b)
CF_c = Segment(C, F_c)
right_a = Angle(B, F_a, A)
right_b = Angle(C, F_b, B)
right_c = Angle(A, F_c, C)

hide(line_AB, line_BC, line_CA, alt_A, alt_B, alt_C)
style(A, B, C, F_a, F_b, F_c, label_visible=True)
style(F_a, label_text="$H_a$")
style(F_b, label_text="$H_b$")
style(F_c, label_text="$H_c$")
style(orthic, fill="color.accent", fill_opacity=0.14)
style(a1, a2, a3, stroke="color.accent", stroke_width_px="line_width.bold")
style(AF_a, BF_b, CF_c, stroke="color.aux", stroke_width_px="line_width.aux")
style(right_a, right_b, right_c, right_angle_marker=True)
