O1 = Point(-1.2, 0)
O2 = Point(1.2, 0)
c1 = Circle(O1, 2.1)
c2 = Circle(O2, 2.1)
X, Y = Intersect(c1, c2)
A = Rotate(X, 1.0, O1)
B = Rotate(X, -1.0, O2)
XA = Segment(X, A)
XB = Segment(X, B)
AB = Segment(A, B)
centers = Segment(O1, O2)

style(O1, O2, X, A, B, label_visible=True)
style(O1, label_text="$O_1$")
style(O2, label_text="$O_2$")
style(Y, label_visible=False, size_px="point_size.aux")
style(c1, c2, stroke="color.aux", stroke_width_px="line_width.main")
style(XA, XB, AB, stroke="color.accent", stroke_width_px="line_width.bold")
style(centers, stroke="color.aux", stroke_width_px="line_width.aux")
