A = Point(-3, -1)
B = Point(3, -1)
C = Point(0, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
M = Midpoint(A, B)
N = Midpoint(A, C)
midline = Segment(M, N)
style(A, B, C, label_visible=True)
style(M, N, label_visible=True, size_px="point_size.aux")
style(midline, BC, stroke="color.accent", stroke_width_px="line_width.bold")
