A = Point(-3.0, -1.5)
B = Point(3.0, -1.2)
C = Point(-0.4, 2.4)
tri, AB, BC, CA = Polygon(A, B, C)
alpha = Angle(B, A, C)
beta = Angle(C, B, A)
gamma = Angle(A, C, B)

style(A, B, C, label_visible=True)
style(alpha, label_visible=True, label_text="$\\alpha$", tick_count=1, arc_size_px=24)
style(beta, label_visible=True, label_text="$\\beta$", tick_count=2, arc_size_px=24)
style(gamma, label_visible=True, label_text="$\\gamma$", tick_count=3, arc_size_px=24)
