O1 = Point(-1.3, 0)
O2 = Point(1.5, 0.3)
c1 = Circle(O1, 2.2)
c2 = Circle(O2, 1.8)
P, Q = Intersect(c1, c2)
radical = Line(P, Q)
centers = Segment(O1, O2)
foot_line = PerpendicularLine(P, centers)

hide(foot_line)
style(O1, O2, P, Q, label_visible=True)
style(O1, label_text="$O_1$")
style(O2, label_text="$O_2$")
style(c1, c2, stroke="color.aux", stroke_width_px="line_width.main")
style(radical, stroke="color.accent", stroke_width_px="line_width.bold")
style(centers, stroke="color.aux", stroke_width_px="line_width.aux")
