F1 = Point(-1.2, 0)
F2 = Point(1.2, 0)
ell = Ellipse(F1, F2, 2.7)
P = Point(3.7, 1.6)
t1, t2 = Tangent(P, ell)
T1 = Intersect(ell, t1)
T2 = Intersect(ell, t2)
seg1 = Segment(P, T1)
seg2 = Segment(P, T2)

hide(t1, t2)
style(F1, F2, P, T1, T2, label_visible=True)
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(T1, label_text="$T_1$")
style(T2, label_text="$T_2$")
style(ell, stroke="color.aux", stroke_width_px=2)
style(seg1, seg2, stroke="color.accent", stroke_width_px="line_width.bold")
