O = Point(0, 0)
A = Point(-2.3, -0.6)
c = Circle(O, A)
B = Rotate(A, -1.35, O)
C = Rotate(A, 1.75, O)
D = Rotate(A, 2.65, O)
chord = Segment(A, B)
AC = Segment(A, C)
BC = Segment(B, C)
AD = Segment(A, D)
BD = Segment(B, D)
angle_C = Angle(A, C, B)
angle_D = Angle(A, D, B)

style(A, B, C, D, O, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(chord, stroke="color.strong", stroke_width_px="line_width.bold")
style(AC, BC, AD, BD, stroke="color.aux", stroke_width_px="line_width.main")
style(angle_C, angle_D, tick_count=1, arc_size_px=24)
