A = Point(-4, -1)
B = Point(4, -1)
C = Point(0, 3)
tri, AB, AC, BC = Polygon(A, B, C)
line_BC = Line(B, C)
D = Point(-1, -1)
t = 0.6
E = Point(-4 + 4*t, -1 + 4*t)
L = Line(D, E)
F = Intersect(L, line_BC)
style(L, stroke="color.accent", stroke_width_px="line_width.bold")
style(line_BC, stroke="color.aux", stroke_width_px="line_width.aux")
style(D, E, F, label_visible=True)
style(A, B, C, label_visible=True)
