A = Point(-3.2, -1.6)
B = Point(3.0, -1.3)
C = Point(-0.6, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
bis_A_line = AngularBisector(B, A, C)
bis_B_line = AngularBisector(C, B, A)
bis_C_line = AngularBisector(A, C, B)
I = Intersect(bis_A_line, bis_B_line)
D = Intersect(bis_A_line, BC)
E = Intersect(bis_B_line, CA)
F = Intersect(bis_C_line, AB)
bis_A = Segment(A, D)
bis_B = Segment(B, E)
bis_C = Segment(C, F)
angle_BAD = Angle(B, A, D)
angle_DAC = Angle(D, A, C)
angle_CBE = Angle(C, B, E)
angle_EBA = Angle(E, B, A)

hide(bis_A_line, bis_B_line, bis_C_line)
style(A, B, C, I, D, E, F, label_visible=True)
style(I, fill="color.accent", size_px="point_size.bold")
style(bis_A, bis_B, bis_C, stroke="color.accent", stroke_width_px="line_width.bold")
style(angle_BAD, angle_DAC, tick_count=1)
style(angle_BAD, arc_size_px=22)
style(angle_DAC, arc_size_px=28)
style(angle_CBE, angle_EBA, tick_count=2)
style(angle_CBE, arc_size_px=22)
style(angle_EBA, arc_size_px=28)
angle_ACF = Angle(A, C, F)
angle_FCB = Angle(F, C, B)
style(angle_ACF, angle_FCB, tick_count=3)
style(angle_ACF, arc_size_px=22)
style(angle_FCB, arc_size_px=28)
