O = Point(0, 0)
A = Point(-2.1, 1.2)
B = Point(2.1, 1.2)
c = Circle(O, A)
chord = Segment(A, B)
M = Midpoint(A, B)
OM = Segment(O, M)
AM = Segment(A, M)
MB = Segment(M, B)
right_M = Angle(A, M, O)

style(O, A, B, M, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(chord, stroke="color.strong", stroke_width_px="line_width.bold")
style(OM, stroke="color.accent", stroke_width_px="line_width.bold")
style(AM, MB, stroke_width_px=0, tick_count=1)
style(right_M, right_angle_marker=True)
