O0 = Point(0, 0)
A = Point(2.6, 0)
c = Circle(O0, A)
B = Rotate(A, 2.1, O0)
C = Rotate(A, 3.5, O0)
D = Rotate(A, 5.1, O0)
chord_AB = Segment(A, B)
chord_CD = Segment(C, D)
M_ab = Midpoint(A, B)
M_cd = Midpoint(C, D)
bis_AB = PerpendicularBisector(A, B)
bis_CD = PerpendicularBisector(C, D)
O = Intersect(bis_AB, bis_CD)
AB_l = Segment(A, M_ab)
AB_r = Segment(M_ab, B)
CD_l = Segment(C, M_cd)
CD_r = Segment(M_cd, D)
right_ab = Angle(A, M_ab, O)
right_cd = Angle(C, M_cd, O)

hide(O0)
style(A, B, C, D, O, label_visible=True)
style(M_ab, M_cd, label_visible=False, size_px="point_size.aux")
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(chord_AB, chord_CD, stroke="color.strong", stroke_width_px="line_width.main")
style(bis_AB, bis_CD, stroke="color.accent", stroke_width_px="line_width.bold")
style(AB_l, AB_r, stroke_width_px=0, tick_count=1)
style(CD_l, CD_r, stroke_width_px=0, tick_count=2)
style(right_ab, right_cd, right_angle_marker=True)
style(O, fill="color.accent", size_px="point_size.bold")
