A = Point(-3.2, -1.4)
B = Point(3.2, -1.4)
C = Point(-0.9, 2.4)

tri, AB, BC, CA = Polygon(A, B, C)
base_line = Line(A, B)
alt_line = PerpendicularLine(C, base_line)
H = Intersect(base_line, alt_line)
height_C = Segment(C, H)
right_H = Angle(A, H, C)

hide(base_line, alt_line)
style(A, B, C, H, label_visible=True)
style(height_C, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_H, right_angle_marker=True)
