O = Point(0, 0)
c = Circle(O, 2.2)
A = Point(3.7, 1.2)
A_inv = Reflect(A, c)
ray = Ray(O, A)
OA = Segment(O, A)
OAi = Segment(O, A_inv)

hide(ray)
style(O, A, A_inv, label_visible=True)
style(A_inv, label_text="$A'$", fill="color.accent", size_px="point_size.bold")
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(OA, stroke="color.aux", stroke_width_px="line_width.aux")
style(OAi, stroke="color.accent", stroke_width_px="line_width.bold")
