A = Point(-2.5, -0.7)
B = Point(-0.2, 1.8)
C = Point(2.6, -0.9)
tri, AB, BC, CA = Polygon(A, B, C)
arc = CircumcircleArc(A, B, C)
circ = Circle(A, B, C)

style(A, B, C, label_visible=True)
style(circ, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
style(arc, stroke="color.accent", stroke_width_px="line_width.bold")
