O = Point(0, 0)
A0 = Point(2.2, 0)
c = Circle(O, A0)
P = Point(4.2, 1.1)
A = Rotate(A0, 0.5, O)
C = Rotate(A0, -1.2, O)
sec1_line = Line(P, A)
sec2_line = Line(P, C)
A1, B1 = Intersect(c, sec1_line)
C1, D1 = Intersect(c, sec2_line)
sec1 = Segment(P, B1)
sec2 = Segment(P, D1)
near1 = Segment(P, A1)
near2 = Segment(P, C1)

hide(sec1_line, sec2_line, A0)
style(O, P, A1, B1, C1, D1, label_visible=True)
style(A1, label_text="$A_1$")
style(B1, label_text="$B_1$")
style(C1, label_text="$C_1$")
style(D1, label_text="$D_1$")
style(sec1, sec2, stroke="color.accent", stroke_width_px="line_width.bold")
style(near1, near2, tick_count=1)
