O = Point(0, 0)
c = Circle(O, 5)
M = Point(2, 0)
line_OM = Line(O, M)
perp = PerpendicularLine(M, line_OM)
P, Q = Intersect(c, perp)
hide(O, line_OM, perp)
PM = Segment(P, M)
MQ = Segment(M, Q)
style(PM, MQ, tick_count=1)
dir1 = Point(3, 1)
line_AB = Line(M, dir1)
A, B = Intersect(c, line_AB)
hide(dir1, line_AB)
dir2 = Point(3, -1)
line_CD = Line(M, dir2)
C, D = Intersect(c, line_CD)
hide(dir2, line_CD)
AB = Segment(A, B)
CD = Segment(C, D)
style(P, Q, M, A, B, C, D, label_visible=True)
