O = Point(0, 0)
A = Point(2, 0)
inner = Circle(O, A)
B = Point(3.5, 0)
outer = Circle(O, B)
inner_radius = Segment(O, A)
outer_radius = Segment(O, B)
style(O, A, B, label_visible=True)
style(inner_radius, stroke="color.accent", stroke_width_px="line_width.bold", label_visible=True, label_text="$r_1$")
style(outer_radius, stroke="color.accent", stroke_width_px="line_width.bold", label_visible=True, label_text="$r_2$")
