A = Point(0, 0)
B = Point(6, 0)
C = Point(5, 3)
D = Point(1, 4)
quad, AB, BC, CD, DA = Polygon(A, B, C, D)
M = Midpoint(A, B)
N = Midpoint(B, C)
P = Midpoint(C, D)
Q = Midpoint(D, A)
MN = Segment(M, N)
NP = Segment(N, P)
PQ = Segment(P, Q)
QM = Segment(Q, M)
AM = Segment(A, M)
MB = Segment(M, B)
BN = Segment(B, N)
NC = Segment(N, C)
CP = Segment(C, P)
PD = Segment(P, D)
DQ = Segment(D, Q)
QA = Segment(Q, A)
style(quad, stroke="color.main", stroke_width_px="line_width.main")
style(MN, NP, PQ, QM, stroke="color.accent", stroke_width_px="line_width.bold")
style(AM, MB, stroke_width_px=0, tick_count=1)
style(BN, NC, stroke_width_px=0, tick_count=2)
style(CP, PD, stroke_width_px=0, tick_count=3)
style(DQ, QA, stroke_width_px=0, tick_count=4)
style(A, B, C, D, M, N, P, Q, label_visible=True)
