A = Point(-3.2, 1.2)
B = Point(-1.2, 1.9)
P = Point(-1.5, -1.5)
Q = Point(2.8, -0.8)
given = Segment(A, B)
ray = Ray(P, Q)
compass = Circle(P, given)
X = Intersect(ray, compass)
copied = Segment(P, X)

style(A, B, P, Q, X, label_visible=True)
style(compass, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
style(given, copied, tick_count=1)
style(copied, stroke="color.accent", stroke_width_px="line_width.bold")
