A = Point(-3.2, -1.6)
B = Point(3.0, -1.2)
C = Point(-0.3, 2.5)
P = Point(0.1, 0.2)
tri, AB, BC, CA = Polygon(A, B, C)
P_star = IsogonalConjugation(A, B, C, P)
AP = Segment(A, P)
BP = Segment(B, P)
CP = Segment(C, P)
APs = Segment(A, P_star)
BPs = Segment(B, P_star)
CPs = Segment(C, P_star)
angle_1 = Angle(B, A, P)
angle_2 = Angle(P_star, A, C)

style(A, B, C, P, P_star, label_visible=True)
style(P_star, label_text="$P^*$", fill="color.accent", size_px="point_size.bold")
style(AP, BP, CP, stroke="color.aux", stroke_width_px="line_width.aux")
style(APs, BPs, CPs, stroke="color.accent", stroke_width_px="line_width.bold")
style(angle_1, angle_2, tick_count=1, arc_size_px=22)
