A = Point(-3.0, -1.0)
B = Point(3.0, -1.0)
C = Point(-0.7, -1.0)
outer = Semicircle(A, B)
left = Semicircle(A, C)
right = Semicircle(C, B)
AB = Segment(A, B)
AC = Segment(A, C)
CB = Segment(C, B)

style(A, B, C, label_visible=True)
style(outer, stroke="color.accent", stroke_width_px="line_width.bold")
style(left, right, stroke="color.strong", stroke_width_px="line_width.bold")
style(AB, AC, CB, stroke="color.aux", stroke_width_px="line_width.aux")
