O = Point(0, 0)
c = Circle(O, 2)
P = Point(4.0, 1.2)
polar = Polar(P, c)
t1, t2 = Tangent(P, c)
T1 = Intersect(c, t1)
T2 = Intersect(c, t2)
chord = Segment(T1, T2)
tangent_1 = Segment(P, T1)
tangent_2 = Segment(P, T2)

hide(t1, t2)
style(O, P, T1, T2, label_visible=True)
style(T1, label_text="$T_1$")
style(T2, label_text="$T_2$")
style(polar, stroke="color.accent", stroke_width_px="line_width.bold")
style(chord, stroke="color.accent", stroke_width_px="line_width.bold")
style(tangent_1, tangent_2, stroke="color.aux", stroke_width_px="line_width.main")
