O = Point(0, 0)
A = Point(-2.1, 0.2)
c = Circle(O, A)
B = Rotate(A, -1.25, O)
C = Rotate(A, 2.2, O)
OA = Segment(O, A)
OB = Segment(O, B)
AC = Segment(A, C)
BC = Segment(B, C)
central = Angle(A, O, B)
inscribed = Angle(A, C, B)

style(O, A, B, C, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(OA, OB, AC, BC, stroke="color.strong", stroke_width_px="line_width.main")
style(central, label_visible=True, label_text="$2\\alpha$", arc_size_px=34)
style(inscribed, label_visible=True, label_text="$\\alpha$", arc_size_px=24)
