O = Point(0, 0)
A = Point(2.5, 0)
c = Circle(O, A)
B = Rotate(A, 2.0, O)
C = Rotate(A, 4.55, O)
OA = Segment(O, A)
OB = Segment(O, B)
chord_CA = Segment(C, A)
chord_CB = Segment(C, B)
central = Angle(A, O, B)
inscribed = Angle(A, C, B)
arc_AB = CircleArc(O, A, B)

style(O, A, B, C, label_visible=True)
style(OA, OB, chord_CA, chord_CB, stroke="color.aux", stroke_width_px="line_width.main")
style(arc_AB, stroke="color.accent", stroke_width_px="line_width.bold")
style(central, label_visible=True, label_text="$2\\alpha$", arc_size_px=30)
style(inscribed, label_visible=True, label_text="$\\alpha$", arc_size_px=22)
