F = Point(0, 1.4)
D1 = Point(-3.2, -1.2)
D2 = Point(3.2, -1.2)
directrix = Line(D1, D2)
parabola = Parabola(F, directrix)
V = Center(parabola)
axis = Axes(parabola)
FV = Segment(F, V)

hide(D1, D2)
style(F, V, label_visible=True)
style(directrix, label_visible=True, label_text="$d$", stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="6 5")
style(parabola, stroke="color.accent", stroke_width_px="line_width.bold")
style(axis, stroke="color.accent", stroke_width_px="line_width.main")
style(FV, stroke="color.aux", stroke_width_px="line_width.aux")
