A = Point(-3.0, -1.5)
B = Point(3.0, -1.2)
C = Point(-0.6, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
circum = Circle(A, B, C)
O = Center(circum)
line_AB = Line(A, B)
line_BC = Line(B, C)
alt_C = PerpendicularLine(C, line_AB)
alt_A = PerpendicularLine(A, line_BC)
H = Intersect(alt_A, alt_C)
N = Midpoint(O, H)
euler = Line(O, H)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
M_ca = Midpoint(C, A)
nine = Circle(M_ab, M_bc, M_ca)

hide(line_AB, line_BC, alt_A, alt_C)
style(A, B, C, O, H, N, label_visible=True)
style(M_ab, M_bc, M_ca, label_visible=False, size_px="point_size.aux")
style(circum, stroke="color.aux", stroke_width_px="line_width.main")
style(nine, stroke="color.accent", stroke_width_px="line_width.bold")
style(euler, stroke="color.strong", stroke_width_px="line_width.bold")
