A = Point(0, 0)
C = Point(5, 0)
B = Point(2, 2)
D = Point(2, -2)
kite, AB, BC, CD, DA = Polygon(A, B, C, D)
diag1 = Segment(A, C)
diag2 = Segment(B, D)
E = Intersect(diag1, diag2)
right_angle = Angle(A, E, D)
style(A, B, C, D, label_visible=True)
style(diag1, diag2, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_angle, right_angle_marker=True)
hide(E)
