A = Point(-3.2, -1.5)
B = Point(3.1, -1.1)
C = Point(-0.6, 2.5)
P = Point(0.8, 0.5)
tri, AB, BC, CA = Polygon(A, B, C)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
p_to_ab = PerpendicularLine(P, line_AB)
p_to_bc = PerpendicularLine(P, line_BC)
p_to_ca = PerpendicularLine(P, line_CA)
F_ab = Intersect(line_AB, p_to_ab)
F_bc = Intersect(line_BC, p_to_bc)
F_ca = Intersect(line_CA, p_to_ca)
pedal, s1, s2, s3 = Polygon(F_ab, F_bc, F_ca)
PF_ab = Segment(P, F_ab)
PF_bc = Segment(P, F_bc)
PF_ca = Segment(P, F_ca)
right_ab = Angle(A, F_ab, P)
right_bc = Angle(B, F_bc, P)
right_ca = Angle(C, F_ca, P)

hide(line_AB, line_BC, line_CA, p_to_ab, p_to_bc, p_to_ca)
style(A, B, C, P, F_ab, F_bc, F_ca, label_visible=True)
style(F_ab, label_text="$P_{AB}$")
style(F_bc, label_text="$P_{BC}$")
style(F_ca, label_text="$P_{CA}$")
style(pedal, fill="color.accent", fill_opacity=0.12)
style(s1, s2, s3, stroke="color.accent", stroke_width_px="line_width.bold")
style(PF_ab, PF_bc, PF_ca, stroke="color.aux", stroke_width_px="line_width.aux")
style(right_ab, right_bc, right_ca, right_angle_marker=True)
