O = Point(0, 0)
T = Point(2.0, 1.0)
c = Circle(O, T)
U = Point(0.8, 3.4)
V = Point(3.2, -1.4)
tangent = Line(U, V)
radius = Segment(O, T)
right_T = Angle(O, T, U)

hide(U, V)
style(O, T, label_visible=True)
style(c, stroke="color.aux", stroke_width_px="line_width.main")
style(tangent, stroke="color.accent", stroke_width_px="line_width.bold")
style(radius, stroke="color.strong", stroke_width_px="line_width.main")
style(right_T, right_angle_marker=True)
