O = Point(0, 0)
A = Point(2.4, 0)
c = Circle(O, A)
B = Rotate(A, 2.1, O)
C = Rotate(A, 4.5, O)
R = Rotate(A, pi / 2, O)
U = A + (R - O) * 1.2
chord = Segment(A, B)
side_CA = Segment(C, A)
side_CB = Segment(C, B)
t = Tangent(A, c)
tangent_seg = Segment(A, U)
angle_tan = Angle(U, A, B)
angle_ins = Angle(A, C, B)

hide(t, R)
style(O, A, B, C, label_visible=True)
style(chord, tangent_seg, stroke="color.accent", stroke_width_px="line_width.bold")
style(side_CA, side_CB, stroke="color.aux", stroke_width_px="line_width.main")
style(angle_tan, angle_ins, tick_count=1)
style(angle_tan, arc_size_px=22)
style(angle_ins, arc_size_px=28)
