A = Point(-1.75, -0.8)
B = Point(1.75, -0.8)
cA = Circle(A, 2.55)
cB = Circle(B, 2.55)
C, D = Intersect(cA, cB)
rhombus, AC, CB, BD, DA = Polygon(A, C, B, D)
diagonal_AB = Segment(A, B)

style(A, B, C, D, label_visible=True)
style(cA, cB, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
style(AC, CB, BD, DA, tick_count=1)
style(diagonal_AB, stroke="color.aux", stroke_width_px="line_width.aux")
