F = Point(2, 0)
d = Line(Point(-2, -5), Point(-2, 5))
parabola = Parabola(F, d)
axis = Axes(parabola)
perp = PerpendicularLine(F, axis)
P1, P2 = Intersect(perp, parabola)
focal_chord = Segment(P1, P2)

style(F, size_px="point_size.bold", fill="color.accent")
style(d, stroke="color.aux", stroke_width_px="line_width.aux")
style(parabola, stroke="color.main", stroke_width_px="line_width.main")
style(focal_chord, stroke="color.accent", stroke_width_px="line_width.bold")
style(P1, P2, size_px="point_size.aux", label_visible=False)
