O = Point(0, 0)
A = Point(2.6, 0)
B = Rotate(A, 1.25, O)
c = Circle(O, A)
sector = CircleSector(O, A, B)
arc = CircleArc(O, A, B)
chord = Segment(A, B)
OA = Segment(O, A)
OB = Segment(O, B)
angle_AOB = Angle(A, O, B)

style(O, A, B, label_visible=True)
style(sector, fill="color.accent", fill_opacity=0.12)
style(arc, stroke="color.accent", stroke_width_px="line_width.bold")
style(chord, stroke="color.strong", stroke_width_px="line_width.bold")
style(OA, OB, stroke="color.aux", stroke_width_px="line_width.main")
style(angle_AOB, label_visible=True, label_text="$\\theta$", arc_size_px=30)
