lemniscate = ImplicitCurve("(x^2 + y^2)^2 - 4*(x^2 - y^2) = 0")
A = Point(-4, -2)
B = Point(4, 2)
line = Line(A, B)
P1, P2, P3 = Intersect(lemniscate, line)
style(lemniscate, stroke="color.main", stroke_width_px="line_width.main")
style(line, stroke="color.aux", stroke_width_px="line_width.aux")
style(P1, P2, P3, label_visible=True, fill="color.accent", size_px="point_size.bold")
hide(A, B)
