A = Point(-2.4, -1.4)
B = Point(2.6, -1.4)
C = Point(-2.4, 1.8)
tri, AB, BC, CA = Polygon(A, B, C)
O = Midpoint(B, C)
circum = Circle(O, B)
OA = Segment(O, A)
OB = Segment(O, B)
OC = Segment(O, C)
BO = Segment(B, O)
OC_half = Segment(O, C)
right_A = Angle(B, A, C)

style(A, B, C, O, label_visible=True)
style(circum, stroke="color.accent", stroke_width_px="line_width.bold")
style(OA, OB, OC, stroke="color.aux", stroke_width_px="line_width.main", tick_count=1)
style(BO, OC_half, stroke_width_px=0, tick_count=2)
style(right_A, right_angle_marker=True)
