A = Point(-3, -1)
B = Point(3, -1)
C = Point(0, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
median_CM = Segment(C, M_ab)
G = Centroid(tri)
seg_CG = Segment(C, G)
seg_GM = Segment(G, M_ab)
AB_left = Segment(A, M_ab)
AB_right = Segment(M_ab, B)
style(A, B, C, label_visible=True)
style(G, label_visible=True, label_text="$G$")
style(M_ab, label_visible=True, label_text="$M_{ab}$")
style(seg_CG, stroke="color.accent", stroke_width_px="line_width.bold", label_visible=True, label_text="$2x$")
style(seg_GM, stroke="color.accent", stroke_width_px="line_width.bold", label_visible=True, label_text="$x$")
style(AB_left, AB_right, stroke_width_px=0, tick_count=1)
hide(median_CM)  # hide original median as parts are shown
