A = Point(-3.1, -1.6)
B = Point(2.9, -1.2)
C = Point(-0.6, 2.5)
tri, AB, BC, CA = Polygon(A, B, C)
M_ab = Midpoint(A, B)
M_bc = Midpoint(B, C)
bis_AB = PerpendicularBisector(A, B)
bis_BC = PerpendicularBisector(B, C)
O = Intersect(bis_AB, bis_BC)
circumcircle = Circle(O, A)
OA = Segment(O, A)
OB = Segment(O, B)
OC = Segment(O, C)
AB_l = Segment(A, M_ab)
AB_r = Segment(M_ab, B)
BC_l = Segment(B, M_bc)
BC_r = Segment(M_bc, C)
right_ab = Angle(A, M_ab, O)
right_bc = Angle(B, M_bc, O)

style(A, B, C, O, label_visible=True)
style(M_ab, M_bc, label_visible=False, size_px="point_size.aux")
style(circumcircle, stroke="color.accent", stroke_width_px="line_width.bold")
style(OA, OB, OC, stroke="color.accent", stroke_width_px="line_width.main", tick_count=1)
style(bis_AB, bis_BC, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="5 5")
style(AB_l, AB_r, stroke_width_px=0, tick_count=2)
style(BC_l, BC_r, stroke_width_px=0, tick_count=3)
style(right_ab, right_bc, right_angle_marker=True)
