A = Point(-4, 0)
B = Point(4, 0)
C = Point(2, 3)
D = Point(-2, 3)
trap, AB, BC, CD, DA = Polygon(A, B, C, D)
angle_DAB = Angle(D, A, B)
angle_ABC = Angle(A, B, C)
angle_ADC = Angle(A, D, C)
angle_BCD = Angle(B, C, D)
style(angle_DAB, angle_ABC, tick_count=1, arc_size_px=20)
style(angle_ADC, angle_BCD, tick_count=2, arc_size_px=25)
style(A, B, C, D, label_visible=True)
hide(trap)
