A = Point(-3, -1)
B = Point(3, -1)
C = Point(-3, 1.2)
D = Point(3, 1.2)
l1 = Line(A, B)
l2 = Line(C, D)
P = Point(-1.8, -1.6)
Q = Point(1.5, 1.8)
transversal = Line(P, Q)
E = Intersect(l1, transversal)
F = Intersect(l2, transversal)
angle_E = Angle(B, E, F)
angle_F = Angle(C, F, E)

hide(A, B, C, D, P, Q)
style(l1, label_visible=True, label_text="$l_1$", stroke="color.strong", stroke_width_px="line_width.bold")
style(l2, label_visible=True, label_text="$l_2$", stroke="color.strong", stroke_width_px="line_width.bold")
style(transversal, stroke="color.accent", stroke_width_px="line_width.bold")
style(E, F, label_visible=True)
style(angle_E, angle_F, tick_count=1, arc_size_px=24)
