A = Point(-4, 0)
C = Point(-1, 0)
B = Point(3, 0)
outer = Semicircle(A, B)
left = Semicircle(A, C)
right = Semicircle(C, B)
AB = Segment(A, B)
AC = Segment(A, C)
CB = Segment(C, B)
style(outer, left, right, stroke="color.main", stroke_width_px="line_width.main")
style(AB, AC, CB, stroke="color.aux", stroke_width_px="line_width.aux")
