A = Point(0, 0)
B = Point(6, 0)
C = Point(4, 3)
D = Point(2, 3)
AB = Segment(A, B)
BC = Segment(B, C)
CD = Segment(C, D)
DA = Segment(D, A)
angleA = Angle(D, A, B)
angleB = Angle(A, B, C)
angleC = Angle(B, C, D)
angleD = Angle(C, D, A)
style(angleA, angleB, tick_count=1, arc_size_px="angle_radius.main")
style(angleC, angleD, tick_count=2, arc_size_px="angle_radius.main")
