O = Point(0, 0)
P = Point(3, 0)
Q = Point(5, 0)
inner = Circle(O, P)
outer = Circle(O, Q)
r_in = Segment(O, P)
r_out = Segment(O, Q)
style(r_in, label_visible=True, label_text="$r_{in}$")
style(r_out, label_visible=True, label_text="$r_{out}$")
style(O, label_visible=True)
style(P, Q, label_visible=False)
