A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
D = Midpoint(A, B)
E = Midpoint(A, C)
DE = Segment(D, E)
style(D, E, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(DE, BC, stroke="color.accent", stroke_width_px="line_width.bold")
style(AB, CA, stroke="color.main", stroke_width_px="line_width.main")
