A = Point(-3, -2)
B = Point(4, -1)
C = Point(3, 3)
D = Point(-2, 2)
quad, AB, BC, CD, DA = Polygon(A, B, C, D)
M_AB = Midpoint(A, B)
M_BC = Midpoint(B, C)
M_CD = Midpoint(C, D)
M_DA = Midpoint(D, A)
varignon, MAB_MBC, MBC_MCD, MCD_MDA, MDA_MAB = Polygon(M_AB, M_BC, M_CD, M_DA)
style(M_AB, M_BC, M_CD, M_DA, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(varignon, stroke="color.accent", stroke_width_px="line_width.bold", fill="color.aux", fill_opacity=0.2)
style(MAB_MBC, MBC_MCD, MCD_MDA, MDA_MAB, stroke="color.accent", stroke_width_px="line_width.bold")
style(quad, stroke="color.main", stroke_width_px="line_width.main", fill="color.aux", fill_opacity=0.1)
style(AB, BC, CD, DA, stroke="color.main", stroke_width_px="line_width.main")
