F1 = Point(-3, 0)
F2 = Point(3, 0)
ellipse = Ellipse(F1, F2, 5)
major_axis = MajorAxis(ellipse)
P, _ = Intersect(ellipse, major_axis)
PF1 = Segment(P, F1)
PF2 = Segment(P, F2)
style(F1, F2, label_visible=True, label_text="$F_1$")
style(F2, label_visible=True, label_text="$F_2$")
style(P, label_visible=True, label_text="$P$")
style(PF1, stroke="color.accent", stroke_width_px="line_width.bold")
style(PF2, stroke="color.accent", stroke_width_px="line_width.bold")
