A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
triangle, AB, BC, CA = Polygon(A, B, C)
incircle = Incircle(A, B, C)
I = Center(incircle)
style(I, label_visible=True, label_text="$I$")
# Perpendicular feet to each side
foot_AB_line = PerpendicularLine(I, AB)
T_AB = Intersect(foot_AB_line, AB)
hide(foot_AB_line)
foot_BC_line = PerpendicularLine(I, BC)
T_BC = Intersect(foot_BC_line, BC)
hide(foot_BC_line)
foot_CA_line = PerpendicularLine(I, CA)
T_CA = Intersect(foot_CA_line, CA)
hide(foot_CA_line)
style(T_AB, label_visible=True, label_text="$T_{AB}$")
style(T_BC, label_visible=True, label_text="$T_{BC}$")
style(T_CA, label_visible=True, label_text="$T_{CA}$")
# Gergonne point: intersection of cevians from vertices to touchpoints
cevian_A = Segment(A, T_BC)
cevian_B = Segment(B, T_CA)
cevian_C = Segment(C, T_AB)
Ge = Intersect(cevian_A, cevian_B)
style(Ge, label_visible=True, label_text="$Ge$", fill="color.accent", size_px="point_size.bold")
style(cevian_A, cevian_B, cevian_C, stroke="color.aux", stroke_width_px="line_width.aux")
# Mark right angles at touchpoints
right_AB = Angle(I, T_AB, B)
style(right_AB, right_angle_marker=True, right_angle_size_px="angle_radius.right")
right_BC = Angle(I, T_BC, C)
style(right_BC, right_angle_marker=True, right_angle_size_px="angle_radius.right")
right_CA = Angle(I, T_CA, A)
style(right_CA, right_angle_marker=True, right_angle_size_px="angle_radius.right")
