A = Point(0, 0)
C = Point(6, 0)
axis = Line(A, C)
B = Point(2, 3)
D = Reflect(B, axis)
AB = Segment(A, B)
AD = Segment(A, D)
CB = Segment(C, B)
CD = Segment(C, D)
BD = Segment(B, D)
AC = Segment(A, C)
right_angle = Angle(B, I, D)
I = Intersect(AC, BD)
style(AB, AD, stroke="color.main", stroke_width_px="line_width.main", tick_count=1)
style(CB, CD, stroke="color.main", stroke_width_px="line_width.main", tick_count=2)
style(BD, AC, stroke="color.accent", stroke_width_px="line_width.bold")
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(axis)
