A = Point(0, 0)
B = Point(3, 0)
pentagon, AB, BC, CD, DE, EA, C, D, E = Polygon(A, B, 5)
AC = Segment(A, C)
AD = Segment(A, D)
BD = Segment(B, D)
BE = Segment(B, E)
CE = Segment(C, E)
style(AC, AD, BD, BE, CE, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, C, D, E, label_visible=True)
