O = Point(0, 0)
P = Point(5, 3)
circle = Circle(O, 3)
t1, t2 = Tangent(P, circle)
T1 = Intersect(t1, circle)
T2 = Intersect(t2, circle)
PT1 = Segment(P, T1)
PT2 = Segment(P, T2)
OT1 = Segment(O, T1)
OT2 = Segment(O, T2)
right1 = Angle(P, T1, O)
right2 = Angle(P, T2, O)
style(O, P, label_visible=True)
style(T1, label_visible=True, label_text="$T_1$")
style(T2, label_visible=True, label_text="$T_2$")
style(PT1, PT2, stroke="color.accent", stroke_width_px="line_width.bold")
style(OT1, OT2, stroke="color.aux", stroke_width_px="line_width.aux")
style(right1, right2, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(t1, t2)
