A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
base_line = Line(A, B)
alt_line = PerpendicularLine(C, base_line)
H = Intersect(alt_line, base_line)
CH = Segment(C, H)
right_angle = Angle(A, H, C)
style(A, B, C, label_visible=True)
style(H, label_visible=True)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(base_line, alt_line)
