O = Point(0, 0)
A = Point(4, 0)
B = Rotate(A, 2.0943951023931953, O)  # 120 degrees
OA = Segment(O, A)
OB = Segment(O, B)
AB = Segment(A, B)
sector = CircleSector(O, A, B)
arc = CircleArc(O, A, B)
angle = Angle(A, O, B)
style(OA, OB, stroke="color.main", stroke_width_px="line_width.main")
style(AB, stroke="color.accent", stroke_width_px="line_width.bold")
style(arc, stroke="color.accent", stroke_width_px="line_width.bold")
style(angle, arc_size_px="angle_radius.main", label_visible=True, label_text="$\\theta$")
