O1 = Point(-1.5, 0)
O2 = Point(1.5, 0)
c1 = Circle(O1, 2.5)
c2 = Circle(O2, 2.5)
P, Q = Intersect(c1, c2)
chord = Segment(P, Q)
arc1 = CircleArc(O1, Q, P)
arc2 = CircleArc(O2, P, Q)
style(O1, O2, label_visible=False, size_px="point_size.aux")
style(chord, stroke="color.main", stroke_width_px="line_width.main")
style(arc1, arc2, stroke="color.accent", stroke_width_px="line_width.bold")
