A = Point(0, 0)
B = Point(4, 0)
C = Point(1, 3)
l = Line(Point(-1, 1), Point(5, 1))
A1 = Reflect(A, l)
B1 = Reflect(B, l)
C1 = Reflect(C, l)
tri, AB, BC, CA = Polygon(A, B, C)
tri1, A1B1, B1C1, C1A1 = Polygon(A1, B1, C1)
style(tri1, stroke="color.accent", stroke_width_px="line_width.bold", fill="color.accent", fill_opacity=0.2)
style(l, stroke="color.aux", stroke_width_px="line_width.aux")
