A = Point(-3, 0)
B = Point(3, 0)
P = Point(1, 3)
AB_line = Line(A, B)
perp = PerpendicularLine(P, AB_line)
H = Intersect(perp, AB_line)
PH = Segment(P, H)
right_angle = Angle(A, H, P)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(AB_line, perp)
style(A, B, P, H, label_visible=True)
