A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
style(A, B, C, label_visible=True)
D = Point(1.5, 0)
F = C + 1.5 * (C - B)
CF = Segment(C, F)
style(CF, stroke="color.aux", stroke_width_px="line_width.aux")
transversal = Line(D, F)
E = Intersect(transversal, CA)
DE = Segment(D, E)
EF = Segment(E, F)
style(transversal, stroke="color.accent", stroke_width_px="line_width.bold")
style(D, E, F, label_visible=True, fill="color.accent", size_px="point_size.bold")
