A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
style(A, B, C, label_visible=True)
angA = Angle(B, A, C)
angB = Angle(C, B, A)
angC = Angle(A, C, B)
style(angA, arc_size_px="angle_radius.main", tick_count=1, label_visible=True, label_text="$\\alpha$")
style(angB, arc_size_px="angle_radius.main", tick_count=2, label_visible=True, label_text="$\\beta$")
style(angC, arc_size_px="angle_radius.main", tick_count=3, label_visible=True, label_text="$\\gamma$")
