O = Point(0, 0)
A = Point(3, 1)
circle = Circle(O, A)
A1 = Reflect(A, circle)
OA = Segment(O, A)
OA1 = Segment(O, A1)
style(OA, OA1, stroke="color.aux", stroke_width_px="line_width.aux")
style(A, A1, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(O, label_visible=True)
hide(OA, OA1)
