A = Point(0, 0)
B = Point(-3, -4)
C = Point(3, -4)
AB = Segment(A, B)
AC = Segment(A, C)
BC = Segment(B, C)
style(A, B, C, label_visible=True)
style(AB, AC, stroke="color.main", stroke_width_px="line_width.main")
style(BC, stroke="color.main", stroke_width_px="line_width.main")
angle_B = Angle(C, B, A)
angle_C = Angle(B, C, A)
style(angle_B, angle_C, arc_size_px="angle_radius.main", tick_count=1)
