A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
style(A, B, C, label_visible=True)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
bis_line = AngularBisector(B, A, C)
D = Intersect(bis_line, BC)
AD = Segment(A, D)
BD = Segment(B, D)
DC = Segment(D, C)
style(AD, stroke="color.accent", stroke_width_px="line_width.bold")
style(BD, DC, stroke="color.accent", stroke_width_px="line_width.bold")
ang1 = Angle(B, A, D)
ang2 = Angle(D, A, C)
style(ang1, ang2, arc_size_px="angle_radius.main", tick_count=1)
hide(bis_line)
