F1 = Point(-3, 0)
F2 = Point(3, 0)
ellipse = Ellipse(F1, F2, 5)
P = Point(0, 5)
t1, t2 = Tangent(P, ellipse)
T1 = Intersect(t1, ellipse)
T2 = Intersect(t2, ellipse)
PT1 = Segment(P, T1)
PT2 = Segment(P, T2)
style(F1, F2, label_visible=True)
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(P, label_visible=True, label_text="$P$")
style(T1, label_visible=True, label_text="$T_1$")
style(T2, label_visible=True, label_text="$T_2$")
style(PT1, PT2, stroke="color.accent", stroke_width_px="line_width.bold")
hide(t1, t2)
