A = Point(0, 0)
B = Point(5, 0)
tri, AB, BC, CA, C = Polygon(A, B, 3)
style(AB, BC, CA, tick_count=1)
angle_A = Angle(B, A, C)
angle_B = Angle(C, B, A)
angle_C = Angle(A, C, B)
style(angle_A, angle_B, angle_C, tick_count=1, arc_size_px="angle_radius.main")
style(A, B, C, label_visible=True)
