O = Point(0, 0)
A = Point(-3, 0)
circle = Circle(O, A)
B = Rotate(A, 2.0943951023931953, O)
AB = Segment(A, B)
C = Rotate(A, 0.8, O)
D = Rotate(A, -1.2, O)
ACB = Angle(A, C, B)
ADB = Angle(A, D, B)
style(ACB, ADB, arc_size_px="angle_radius.main", tick_count=1)
style(A, B, C, D, label_visible=True)
style(O, label_visible=False)
hide(O)
