O = Point(0, 0)
A = Point(-3, 0)
circle = Circle(O, A)
B = Rotate(A, 0.8, O)
C = Rotate(A, 2.0, O)
D = Rotate(A, 3.5, O)
chord1 = Segment(A, B)
chord2 = Segment(C, D)
E = Intersect(chord1, chord2)
style(E, label_visible=True, fill="color.accent", size_px="point_size.bold")
