A = Point(0, 0)
B = Point(6, 0)
C = Point(4, 3)
D = Point(1, 3)
AB = Segment(A, B)
BC = Segment(B, C)
CD = Segment(C, D)
DA = Segment(D, A)
M = Midpoint(A, D)
N = Midpoint(B, C)
MN = Segment(M, N)
style(M, N, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(MN, stroke="color.accent", stroke_width_px="line_width.bold")
AM = Segment(A, M)
MD = Segment(M, D)
BN = Segment(B, N)
NC = Segment(N, C)
style(AM, MD, BN, NC, stroke_width_px=0, tick_count=1)
style(AM, MD, BN, NC, tick_length_px="tick.main")
