O = Point(0, 0)
circle = Circle(O, 4)
P = Point(-6, 0)
t1, t2 = Tangent(P, circle)
T = Intersect(t1, circle)
PT = Segment(P, T)
line = Line(P, O)
A, B = Intersect(line, circle)
PA = Segment(P, A)
PB = Segment(P, B)
AB = Segment(A, B)
OT = Segment(O, T)
right_angle = Angle(P, T, O)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(OT, stroke="color.aux", stroke_width_px="line_width.aux")
style(PT, stroke="color.accent", stroke_width_px="line_width.bold")
style(PA, PB, stroke="color.main", stroke_width_px="line_width.main")
hide(t1, t2, line)
label_text = "$PT^2 = PA \\cdot PB$"
style(PT, label_visible=True, label_text=label_text)
