A = Point(-3, -2)
B = Point(4, -1)
C = Point(1, 3)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
triangle, AB, BC, CA = Polygon(A, B, C)
M_AB = Midpoint(A, B)
M_BC = Midpoint(B, C)
M_CA = Midpoint(C, A)
median_A = Line(A, M_BC)
median_B = Line(B, M_CA)
G = Intersect(median_A, median_B)
style(G, label_visible=True, label_text="$G$", fill="color.accent", size_px="point_size.bold")
hide(median_A, median_B, M_AB, M_BC, M_CA)
K = IsogonalConjugation(A, B, C, G)
style(K, label_visible=True, label_text="$K$", fill="color.accent", size_px="point_size.bold")
AK = Segment(A, K)
BK = Segment(B, K)
CK = Segment(C, K)
style(AK, BK, CK, stroke="color.accent", stroke_width_px="line_width.bold")
