O1 = Point(-2, 0)
O2 = Point(2, 0)
P = Point(-1, 2)
Q = Point(1, 2)
c1 = Circle(O1, P)
c2 = Circle(O2, Q)
P12, Q12 = Intersect(c1, c2)
radical_axis = Line(P12, Q12)
center_line = Segment(O1, O2)
style(O1, O2, label_visible=True)
style(P12, Q12, label_visible=False, fill="color.aux", size_px="point_size.aux")
style(radical_axis, stroke="color.accent", stroke_width_px="line_width.bold")
style(center_line, stroke="color.aux", stroke_width_px="line_width.aux")
style(c1, c2, stroke="color.main")
