O = Point(0, 0)
A = Point(-2.1, 1.7)
circle = Circle(O, A)
B = Rotate(A, 2.0, O)
AB = Segment(A, B)
perp_line = PerpendicularLine(O, AB)
H = Intersect(perp_line, AB)
OH = Segment(O, H)
AH = Segment(A, H)
HB = Segment(H, B)
right_angle = Angle(A, H, O)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(AH, HB, stroke="color.accent", stroke_width_px="line_width.bold", tick_count=1)
hide(perp_line)
