A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
triangle, AB, BC, CA = Polygon(A, B, C)
incircle = Incircle(A, B, C)
I = Center(incircle)
style(A, B, C, label_visible=True)
style(I, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(incircle, stroke="color.aux", stroke_width_px="line_width.aux")
