A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
M = Midpoint(B, C)
AM = Segment(A, M)
G = Intersect(AM, AM)
AG = Segment(A, G)
GM = Segment(G, M)
style(AG, label_text="$2x$")
style(GM, label_text="$x$")
style(G, fill="color.accent", size_px="point_size.bold", label_visible=True)
style(M, label_visible=True)
style(AM, stroke="color.accent", stroke_width_px="line_width.bold")
