A = Point(-3, -2)
B = Point(4, -1)
C = Point(0, 3)
triangle, AB, BC, CA = Polygon(A, B, C)
circ = Circumcircle(A, B, C)
P = Point(2.5, 3.8)
# Ensure P is on circumcircle by construction: rotate A around center
O = Center(circ)
P = Rotate(A, 1.2, O)
# Perpendicular feet to side lines
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
perp_P_AB = PerpendicularLine(P, line_AB)
perp_P_BC = PerpendicularLine(P, line_BC)
perp_P_CA = PerpendicularLine(P, line_CA)
F_AB = Intersect(perp_P_AB, line_AB)
F_BC = Intersect(perp_P_BC, line_BC)
F_CA = Intersect(perp_P_CA, line_CA)
# Simson line through two feet (third is collinear)
simson = Line(F_AB, F_BC)
# Style
style(A, B, C, P, label_visible=True)
style(F_AB, F_BC, F_CA, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(simson, stroke="color.accent", stroke_width_px="line_width.bold")
hide(line_AB, line_BC, line_CA, perp_P_AB, perp_P_BC, perp_P_CA)
style(triangle, fill="color.aux", fill_opacity=0.1)
style(circ, stroke="color.aux")
