A = Point(-2, -1)
B = Point(2, -1)
C = Point(0, 2)
O = Point(0, 0)
k = 1.6
A1 = O + k * (A - O)
B1 = O + k * (B - O)
C1 = O + k * (C - O)
tri, AB, BC, CA = Polygon(A, B, C)
tri1, A1B1, B1C1, C1A1 = Polygon(A1, B1, C1)
style(A, B, C, label_visible=True)
style(A1, B1, C1, label_visible=True)
style(tri, tri1, fill="color.aux", stroke="color.main", stroke_width_px="line_width.main")
style(A1B1, B1C1, C1A1, stroke="color.accent", stroke_width_px="line_width.bold")
