A = Point(0, 0)
B = Point(6, 0)
tri, AB, BC, CA, C = Polygon(A, B, 3)
P = Point(3, 1.5)
line_AB = Line(A, B)
line_BC = Line(B, C)
line_CA = Line(C, A)
perp_AB = PerpendicularLine(P, line_AB)
perp_BC = PerpendicularLine(P, line_BC)
perp_CA = PerpendicularLine(P, line_CA)
F_AB = Intersect(perp_AB, line_AB)
F_BC = Intersect(perp_BC, line_BC)
F_CA = Intersect(perp_CA, line_CA)
seg_P_AB = Segment(P, F_AB)
seg_P_BC = Segment(P, F_BC)
seg_P_CA = Segment(P, F_CA)
right_AB = Angle(F_AB, P, A)
right_BC = Angle(F_BC, P, B)
right_CA = Angle(F_CA, P, C)
style(right_AB, right_BC, right_CA, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(seg_P_AB, seg_P_BC, seg_P_CA, stroke="color.accent", stroke_width_px="line_width.bold")
style(P, fill="color.accent", size_px="point_size.bold", label_visible=True)
style(F_AB, F_BC, F_CA, fill="color.aux", size_px="point_size.aux", label_visible=False)
hide(perp_AB, perp_BC, perp_CA, line_AB, line_BC, line_CA)
