A = Point(0, 0)
B = Point(6, 0)
C = Point(0, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
right_angle = Angle(A, C, B)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
M = Midpoint(A, B)
circumcircle = Circle(M, A)
MA = Segment(M, A)
MB = Segment(M, B)
MC = Segment(M, C)
style(MA, MB, MC, stroke="color.accent", stroke_width_px="line_width.bold", tick_count=1)
style(M, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(A, B, C, label_visible=True)
