A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 4)
style(A, B, C, label_visible=True)
P = Point(3, 1.5)
style(P, label_visible=True, fill="color.accent", size_px="point_size.bold")
tri, AB, BC, CA = Polygon(A, B, C)
style(tri, fill="color.aux", fill_opacity=0.1, stroke="color.main", stroke_width_px="line_width.main")
AP = Segment(A, P)
BP = Segment(B, P)
CP = Segment(C, P)
style(AP, BP, CP, stroke="color.accent", stroke_width_px="line_width.bold")
