A = Point(-2, -1)
B = Point(2, -1)
C = Point(1.5, 1.5)
D = Point(-1.5, 1.5)
quad, AB, BC, CD, DA = Polygon(A, B, C, D)
circle = Circle(A, B, C)
style(circle, stroke="color.aux", stroke_width_px="line_width.aux")
angA = Angle(D, A, B)
angC = Angle(B, C, D)
style(angA, angC, arc_size_px="angle_radius.main", tick_count=1)
angB = Angle(A, B, C)
angD = Angle(C, D, A)
style(angB, angD, arc_size_px="angle_radius.main", tick_count=2)
style(A, B, C, D, label_visible=True)
