A = Point(0, 0)
B = Point(5, 0)
D = Point(2, 3)
AB = Segment(A, B)
AD = Segment(A, D)
C = D + (B - A)
BC = Segment(B, C)
CD = Segment(C, D)
AC = Segment(A, C)
BD = Segment(B, D)
O = Intersect(AC, BD)
AO = Segment(A, O)
OC = Segment(O, C)
BO = Segment(B, O)
OD = Segment(O, D)
style(A, B, C, D, label_visible=True)
style(O, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(AO, OC, tick_count=1, stroke="color.aux", stroke_width_px="line_width.aux")
style(BO, OD, tick_count=2, stroke="color.aux", stroke_width_px="line_width.aux")
style(AC, BD, stroke="color.accent", stroke_width_px="line_width.bold")
