F = Point(0, 0)
style(F, label_visible=True, label_text="$F$")
d = Line(Point(-4, -2), Point(4, -2))
style(d, label_visible=True, label_text="d")
p = Parabola(F, d)
style(p, stroke="color.accent", stroke_width_px="line_width.bold")
axis = Axes(p)
style(axis, stroke="color.aux", stroke_width_px="line_width.aux")
V = Center(p)
style(V, label_visible=True, label_text="$V$")
P1 = Intersect(p, axis)
P2 = Intersect(p, axis, index=2)
chord = Segment(P1, P2)
style(chord, stroke="color.strong", stroke_width_px="line_width.main")
right_angle = Angle(P1, F, V)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
