O = Point(0, 0)
P = Point(-2.1, 1.7)
Q = Point(2.1, 1.7)
circle = Circle(O, P)
chord = Segment(P, Q)
arc_PQ = CircleArc(O, Q, P)
style(P, Q, label_visible=True)
style(chord, stroke="color.main", stroke_width_px="line_width.main")
style(arc_PQ, stroke="color.accent", stroke_width_px="line_width.bold")
