A = Point(0, 0)
B = Point(4, 0)
AB = Segment(A, B)
P = Point(1, 2)
Q = Point(5, 2)
ray = Ray(P, Q)
circle = Circle(P, A, B)
C = Intersect(circle, ray)
PC = Segment(P, C)
style(AB, PC, stroke="color.main", stroke_width_px="line_width.main", tick_count=1)
style(A, B, P, Q, C, label_visible=True)
hide(circle)
