O = Point(0, 0)
A = Point(3, 0)
circle = Circle(O, A)
P = Point(-1, 4)
t1, t2 = Tangent(P, circle)
T1 = Intersect(t1, circle)
T2 = Intersect(t2, circle)
PT1 = Segment(P, T1)
PT2 = Segment(P, T2)
OT1 = Segment(O, T1)
OT2 = Segment(O, T2)
right1 = Angle(P, T1, O)
right2 = Angle(P, T2, O)
style(right1, right2, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(OT1, OT2, stroke="color.aux", stroke_width_px="line_width.aux")
style(PT1, PT2, stroke="color.accent", stroke_width_px="line_width.bold", tick_count=1)
style(T1, T2, label_visible=True, fill="color.accent", size_px="point_size.bold")
hide(t1, t2)
