A = Point(-2, 0)
B = Point(2, 0)
AB = Segment(A, B)
style(A, B, label_visible=True)
style(AB, stroke="color.aux", stroke_width_px="line_width.aux")
r = 3.5
cA = Circle(A, r)
cB = Circle(B, r)
C, D = Intersect(cA, cB)
AC = Segment(A, C)
CB = Segment(C, B)
BD = Segment(B, D)
DA = Segment(D, A)
style(AC, CB, BD, DA, stroke="color.main", stroke_width_px="line_width.main", tick_count=1)
style(C, D, label_visible=True)
hide(cA, cB)
