A = Point(-3, -2)
B = Point(3, -2)
tri, AB, BC, CA, C = Polygon(A, B, 3)
M_AB = Midpoint(A, B)
M_BC = Midpoint(B, C)
M_CA = Midpoint(C, A)
median_A = Segment(A, M_BC)
median_B = Segment(B, M_CA)
median_C = Segment(C, M_AB)
G = Intersect(median_A, median_B)
AM_BC = Segment(A, M_BC)
BM_CA = Segment(B, M_CA)
CM_AB = Segment(C, M_AB)
AG = Segment(A, G)
GM_BC = Segment(G, M_BC)
BG = Segment(B, G)
GM_CA = Segment(G, M_CA)
CG = Segment(C, G)
GM_AB = Segment(G, M_AB)
style(AG, GM_BC, tick_count=1)
style(BG, GM_CA, tick_count=1)
style(CG, GM_AB, tick_count=1)
style(A, B, C, label_visible=True)
style(M_AB, M_BC, M_CA, label_visible=True, fill="color.aux", size_px="point_size.aux")
style(G, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(median_A, median_B, median_C, stroke="color.accent", stroke_width_px="line_width.bold")
hide(tri)
