F = Point(2, 0)
P = Point(-3, 2)
Q = Point(-3, -2)
d = Line(P, Q)
parabola = Parabola(F, d)
axis = Axes(parabola)
vertex = Center(parabola)
style(F, label_visible=True, label_text="$F$")
style(d, label_visible=True, label_text="$d$")
style(axis, label_visible=True, label_text="$l$")
style(vertex, label_visible=True, label_text="$V$")
