A = Point(-3, 0)
B = Point(3, 0)
AB = Segment(A, B)
c1 = Circle(A, B)
c2 = Circle(B, A)
P, Q = Intersect(c1, c2)
perp_bisector = Line(P, Q)
M = Intersect(perp_bisector, AB)
AM = Segment(A, M)
MB = Segment(M, B)
right_angle = Angle(P, M, A)
style(AM, MB, tick_count=1)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(P, Q, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(M, label_visible=True, fill="color.strong", size_px="point_size.bold")
style(perp_bisector, stroke="color.accent", stroke_width_px="line_width.bold")
