A = Point(-2, -2)
B = Point(2, -2)
C = Point(2, 2)
D = Point(-2, 2)
square, AB, BC, CD, DA = Polygon(A, B, C, D)
AC = Segment(A, C)
BD = Segment(B, D)
O = Intersect(AC, BD)
style(AC, BD, stroke="color.aux", stroke_width_px="line_width.aux")
style(O, label_visible=True, fill="color.accent", size_px="point_size.bold")
