A = Point(-3, 0)
B = Point(3, 0)
AB = Segment(A, B)
semi = Semicircle(A, B)
C = Point(0, 2.5)
AC = Segment(A, C)
BC = Segment(B, C)
right_angle = Angle(A, C, B)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(A, B, C, label_visible=True)
