O = Point(0, 0)
T = Point(2.5, 0)
circle = Circle(O, T)
tangent_line = Tangent(T, circle)
OT = Segment(O, T)
right_angle = Angle(O, T, tangent_line)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
style(OT, stroke="color.main", stroke_width_px="line_width.main")
style(tangent_line, stroke="color.accent", stroke_width_px="line_width.bold")
hide(tangent_line)
