O = Point(0, 0)
A = Point(-3, 0)
B = Rotate(A, 2.0943951023931953, O)
C = Rotate(A, 1.0471975511965976, O)
circle = Circle(O, A)
OA = Segment(O, A)
OB = Segment(O, B)
CA = Segment(C, A)
CB = Segment(C, B)
central = Angle(A, O, B)
inscribed = Angle(A, C, B)
style(central, label_visible=True, label_text="$2\\alpha$", arc_size_px="angle_radius.main")
style(inscribed, label_visible=True, label_text="$\\alpha$", arc_size_px="angle_radius.aux")
style(A, B, C, O, label_visible=True)
style(OA, OB, CA, CB, stroke="color.main", stroke_width_px="line_width.main")
style(circle, stroke="color.aux", stroke_width_px="line_width.aux")
