F1 = Point(-2, 0)
F2 = Point(2, 0)
hyperbola = Hyperbola(F1, F2, 1.2)
center = Center(hyperbola)
major_axis = MajorAxis(hyperbola)
minor_axis = MinorAxis(hyperbola)
vertices = Vertex(hyperbola)
style(F1, label_visible=True, label_text="$F_1$")
style(F2, label_visible=True, label_text="$F_2$")
style(center, label_visible=True, label_text="$O$")
style(vertices, label_visible=True, label_text="$V$")
style(major_axis, stroke="color.main", stroke_width_px="line_width.main")
style(minor_axis, stroke="color.aux", stroke_width_px="line_width.aux")
