A = Point(-3, 0)
B = Point(3, 0)
line1 = Line(A, B)
C = Point(-2, 2)
line2 = Line(C, line1)
D = Point(-4, -1)
E = Point(4, 1)
secant = Line(D, E)
P = Intersect(secant, line1)
Q = Intersect(secant, line2)
ang1 = Angle(P, Q, C)
ang2 = Angle(A, P, Q)
style(ang1, ang2, arc_size_px="angle_radius.main", tick_count=1)
style(line1, line2, secant, stroke="color.main", stroke_width_px="line_width.main")
style(A, B, C, D, E, label_visible=False)
style(P, Q, label_visible=True)
