F1 = Point(-2, 0)
F2 = Point(2, 0)
ellipse = Ellipse(F1, F2, 3)
center = Center(ellipse)
major_axis = MajorAxis(ellipse)
minor_axis = MinorAxis(ellipse)
style(F1, label_visible=True, label_text="$F_1$", fill="color.accent", size_px="point_size.bold")
style(F2, label_visible=True, label_text="$F_2$", fill="color.accent", size_px="point_size.bold")
style(center, label_visible=True, label_text="$O$", fill="color.main", size_px="point_size.main")
style(major_axis, stroke="color.main", stroke_width_px="line_width.main")
style(minor_axis, stroke="color.aux", stroke_width_px="line_width.aux")
