A = Point(0, 0)
B = Point(5, 0)
C = Point(2, 4)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
triangle, AB, BC, CA = Polygon(A, B, C)
bisector_line = AngularBisector(B, A, C)
D = Intersect(bisector_line, BC)
AD = Segment(A, D)
hide(bisector_line)
style(AD, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, C, label_visible=True)
style(D, label_visible=True, fill="color.accent", size_px="point_size.bold")
angle1 = Angle(B, A, D)
angle2 = Angle(D, A, C)
style(angle1, angle2, arc_size_px="angle_radius.main", tick_count=1)
