A = Point(-2, 0)
C = Point(2, 0)
axis = Line(A, C)
B = Point(0, 1.5)
D = Reflect(B, axis)
quad, AB, BC, CD, DA = Polygon(A, B, C, D)
style(A, B, C, D, label_visible=True)
style(AB, BC, CD, DA, stroke="color.main", stroke_width_px="line_width.main")
style(AB, AD, tick_count=1)
style(CB, CD, tick_count=2)
style(axis, stroke="color.aux", stroke_width_px="line_width.aux", label_visible=True)
AC = Segment(A, C)
style(AC, stroke="color.accent", stroke_width_px="line_width.bold")
