O = Point(0, 0)
A = Point(3, 0)
B = Rotate(A, 2.0943951023931953, O)
circle = Circle(O, A)
sector = CircleSector(O, A, B)
OA = Segment(O, A)
OB = Segment(O, B)
central_angle = Angle(A, O, B)
style(OA, OB, stroke="color.accent", stroke_width_px="line_width.bold")
style(central_angle, arc_size_px="angle_radius.main", label_visible=True, label_text="$\\theta$")
style(A, B, label_visible=True)
style(O, label_visible=True)
hide(circle)
