O = Point(0, 0)
A = Point(1, 0)
B = Point(0, 1)
x_axis = Line(O, A)
y_axis = Line(O, B)
circle = Circle(O, A)
P = Rotate(A, pi / 3, O)

cos_line = PerpendicularLine(P, x_axis)
sin_line = PerpendicularLine(P, y_axis)
foot_x = Intersect(cos_line, x_axis)
foot_y = Intersect(sin_line, y_axis)

cos_seg = Segment(O, foot_x)
sin_seg = Segment(O, foot_y)
proj_x = Segment(P, foot_x)
proj_y = Segment(P, foot_y)
OP = Segment(O, P)

style(circle, stroke="color.main", stroke_width_px="line_width.main")
style(x_axis, y_axis, stroke="color.aux", stroke_width_px="line_width.aux")
style(cos_seg, stroke="color.accent", stroke_width_px="line_width.bold", label_text="$\\cos\\theta$", label_visible=True)
style(sin_seg, stroke="color.accent", stroke_width_px="line_width.bold", label_text="$\\sin\\theta$", label_visible=True)
style(proj_x, proj_y, stroke="color.aux", stroke_width_px="line_width.aux", stroke_dasharray="4 2")
style(OP, stroke="color.aux", stroke_width_px="line_width.aux")
style(O, A, P, label_visible=True)
style(B, foot_x, foot_y, label_visible=False, size_px="point_size.aux")

right_x = Angle(A, foot_x, P)
right_y = Angle(B, foot_y, P)
style(right_x, right_y, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(cos_line, sin_line)
