O = Point(0, 0)
A = Point(3, 0)
circle = Circle(O, A)
hexagon, AB, BC, CD, DE, EF, FA, B, C, D, E, F = Polygon(A, B, 6)
OA = Segment(O, A)
OB = Segment(O, B)
OC = Segment(O, C)
OD = Segment(O, D)
OE = Segment(O, E)
OF = Segment(O, F)
style(OA, OB, OC, OD, OE, OF, tick_count=1)
style(AB, BC, CD, DE, EF, FA, tick_count=2)
style(hexagon, fill="color.aux", fill_opacity=0.1)
hide(circle)
