A = Point(-3, 1)
B = Point(2, 1)
C = Point(0, 0)
tri, AB, BC, CA = Polygon(A, B, C)
int_bis = AngularBisector(A, C, B)
ext_bis = OrthogonalLine(C, int_bis)
perp_from_B = OrthogonalLine(B, ext_bis)
T = Intersect(ext_bis, perp_from_B)
circle = Circle(B, T)
hide(int_bis)
style(ext_bis, label_visible=True, label_text="$l$", stroke="color.aux")
style(circle, stroke="color.accent", stroke_width_px="line_width.bold")
style(T, label_visible=False, size_px="point_size.aux")
