O = Point(0, 0)
circle = Circle(O, 2)
T = Point(2, 0)
style(T, label_visible=True, label_text="$T$")
style(O, label_visible=True, label_text="$O$")
OT = Segment(O, T)
style(OT, stroke="color.aux", stroke_width_px="line_width.aux")
tangent_line = Tangent(T, circle)
style(tangent_line, stroke="color.accent", stroke_width_px="line_width.bold")
right_angle = Angle(O, T, tangent_line)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
