O = Point(0, 0)
A = Point(3, 0)
B = Rotate(A, 2 * pi / 3, O)
circle = Circle(O, A)
sector = CircleSector(O, A, B)
OA = Segment(O, A)
OB = Segment(O, B)
chord = Segment(A, B)
arc = CircleArc(O, A, B)
central_angle = Angle(A, O, B)
style(sector, stroke="color.main", stroke_width_px="line_width.main", fill="color.aux", fill_opacity=0.2)
style(OA, OB, stroke="color.accent", stroke_width_px="line_width.bold")
style(chord, stroke="color.accent", stroke_width_px="line_width.bold")
style(arc, stroke="color.accent", stroke_width_px="line_width.bold")
style(central_angle, arc_size_px="angle_radius.bold", label_visible=True, label_text="$\\angle AOB$")
style(O, A, B, label_visible=True, fill="color.main", size_px="point_size.main")
hide(circle)
