A = Point(0, 2)
B = Point(1.9, 0.62)
pentagon, AB, BC, CD, DE, EA, C, D, E = Polygon(A, B, 5)
style(pentagon, stroke="color.main", stroke_width_px="line_width.main", fill="color.aux", fill_opacity=0.15)
style(AB, BC, CD, DE, EA, stroke="color.main", stroke_width_px="line_width.main")
AC = Segment(A, C)
AD = Segment(A, D)
BD = Segment(B, D)
BE = Segment(B, E)
CE = Segment(C, E)
style(AC, AD, BD, BE, CE, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, C, D, E, label_visible=True, fill="color.strong", size_px="point_size.bold")
