A = Point(0, 0)
B = Point(3, 1)
P = Point(1, 3)
AB = Line(A, B)
parallel = Line(P, AB)
style(AB, stroke="color.main", stroke_width_px="line_width.main")
style(parallel, stroke="color.accent", stroke_width_px="line_width.bold")
style(A, B, P, label_visible=True)
style(parallel, label_visible=True, label_text="$l$")
