O = Point(0, 0)
A = Point(2, 1)
circle = Circle(O, A)
A1 = Reflect(A, circle)
OA = Segment(O, A)
OA1 = Segment(O, A1)
style(A, label_visible=True)
style(O, label_visible=True)
style(A1, label_visible=True, label_text="$A'$")
style(OA, OA1, stroke="color.aux", stroke_width_px="line_width.aux")
style(circle, stroke="color.main", stroke_width_px="line_width.main")
