F1 = Point(-2, 0)
F2 = Point(2, 0)
ellipse = Ellipse(F1, F2, 3)
center = Center(ellipse)
major_axis = MajorAxis(ellipse)
minor_axis = MinorAxis(ellipse)
style(F1, F2, label_visible=True, fill="color.strong", size_px="point_size.bold")
style(F1, label_text="$F_1$")
style(F2, label_text="$F_2$")
style(center, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(major_axis, minor_axis, stroke="color.aux", stroke_width_px="line_width.aux")
style(ellipse, stroke="color.main", stroke_width_px="line_width.main")
