F = Point(1, 0)
A = Point(-1, 0)
B = Point(-1, 2)
d = Line(A, B)
parabola = Parabola(F, d)
V = Center(parabola)
axis = Axes(parabola)
style(F, label_visible=True, fill="color.strong", size_px="point_size.bold")
style(d, stroke="color.aux", stroke_width_px="line_width.aux", label_visible=True)
style(parabola, stroke="color.accent", stroke_width_px="line_width.bold")
style(V, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(axis, stroke="color.aux", stroke_width_px="line_width.aux", label_visible=True)
hide(A, B)
