A = Point(0, 0)
B = Point(6, 0)
C = Point(2, 5)
AB = Segment(A, B)
BC = Segment(B, C)
CA = Segment(C, A)
style(AB, BC, CA, stroke="color.main", stroke_width_px="line_width.main")
base_line = Line(A, B)
alt_line = PerpendicularLine(C, base_line)
H = Intersect(alt_line, base_line)
CH = Segment(C, H)
style(CH, stroke="color.accent", stroke_width_px="line_width.bold")
right_angle = Angle(A, H, C)
style(right_angle, right_angle_marker=True, right_angle_size_px="angle_radius.right")
hide(base_line, alt_line)
style(H, label_visible=True, fill="color.accent", size_px="point_size.bold")
style(A, B, C, label_visible=True, fill="color.strong", size_px="point_size.main")
