"""CLI entry point: ``python -m animageo file.ggb -o out.svg``.

Renders a GeoGebra ``.ggb`` file into one of two tracks:

- **static vector** (``svg`` / ``pdf`` / ``eps`` / ``tikz``) — the construction
  is built once and serialised by an ``export*`` method;
- **render** (``png`` / ``gif`` / ``mp4`` / ``webm`` / ``mov``) — manim's own
  renderer writes the artifact; pass ``--keyframes`` to animate (otherwise a
  single frame is produced).

A small driver script is written to a private temporary directory and ``manim``
is invoked through ``subprocess.run`` with an argv list — no shell
interpolation, every user string is embedded via ``repr()``. The export format
is chosen by ``--format`` or inferred from the output extension.
"""
import argparse
import glob
import logging
import os
import shutil
import subprocess
import sys
import tempfile

from .logging_config import configure_logging, LOG_LEVELS
from .style.config import resolve_style_input

logger = logging.getLogger(__name__)


# Static vector formats are written by an AnimaGeoScene.export* method after
# construct(); render formats are produced by manim's renderer.
STATIC_FORMATS = ("svg", "pdf", "eps", "tikz", "jsxgraph")
RENDER_FORMATS = ("png", "gif", "mp4", "webm", "mov")
ALL_FORMATS = STATIC_FORMATS + RENDER_FORMATS

EXT_BY_FORMAT = {
    "svg": ".svg", "pdf": ".pdf", "eps": ".eps", "tikz": ".tex", "jsxgraph": ".html",
    "png": ".png", "gif": ".gif", "mp4": ".mp4", "webm": ".webm", "mov": ".mov",
}
FORMAT_BY_EXT = {ext: fmt for fmt, ext in EXT_BY_FORMAT.items()}


_DRIVER_TEMPLATE = """\
# autogenerated by AnimaGeo CLI — do not edit
from animageo import AnimaGeoScene


class Scene_(AnimaGeoScene):
    def construct(self):
        self.loadGGB(
            {ggbfile!r},
            style={style!r},
            reference={reference!r},
            content={content!r},
            export={export!r},
            debug={debug!r},
            generate_stubs=False,
        )
        {export_call}
"""


_RENDER_DRIVER_TEMPLATE = """\
# autogenerated by AnimaGeo CLI — do not edit
import json

from animageo import AnimaGeoScene


class Scene_(AnimaGeoScene):
    def construct(self):
        self.loadGGB(
            {ggbfile!r},
            style={style!r},
            reference={reference!r},
            content={content!r},
            export={export!r},
            debug={debug!r},
            generate_stubs=False,
        )
        {play_call}
"""


def _manim_env():
    """Environment for the ``manim`` subprocess.

    The driver is written to a temp dir, so manim's interpreter would not see
    the ``animageo`` package when it is run from a source checkout (rather than
    pip-installed). Prepend the package's parent dir to ``PYTHONPATH`` so the
    driver's ``from animageo import AnimaGeoScene`` resolves either way.
    """
    env = os.environ.copy()
    pkg_parent = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    existing = env.get('PYTHONPATH', '')
    env['PYTHONPATH'] = pkg_parent + (os.pathsep + existing if existing else '')
    return env


def _find_rendered_file(root, ext):
    """Return the newest ``*<ext>`` file produced under ``root`` (manim media)."""
    matches = glob.glob(os.path.join(root, "**", "*" + ext), recursive=True)
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


def _parse_size(raw):
    """Accept ['640', '480'] or ['auto', 'auto']. Returns list[int]|list[str]."""
    if raw is None:
        return None
    out = []
    for v in raw:
        if v == 'auto':
            out.append('auto')
        else:
            out.append(int(v))
    return out


def _parse_float_pair(raw):
    if raw is None:
        return None
    return [float(raw[0]), float(raw[1])]


def _resolve_format(args):
    """Resolve the export format: explicit --format > -o extension > svg."""
    fmt = args.format
    if fmt is None and args.output:
        ext = os.path.splitext(args.output)[1].lower()
        fmt = FORMAT_BY_EXT.get(ext)
    if fmt is None:
        fmt = 'svg'
    return fmt


def _resolve_style_arg(raw):
    """Resolve a CLI style argument to a usable absolute/package path.

    Bare names such as ``default`` are allowed when they identify a packaged
    preset. Other values must point to an existing file. ``None`` keeps the
    historical empty-string sentinel used by the generated driver.
    """
    if not raw:
        return ''
    resolved = resolve_style_input(raw)
    if resolved != raw:
        return resolved
    path = os.path.abspath(raw)
    return path if os.path.isfile(path) else None


def main():
    parser = argparse.ArgumentParser(
        prog='animageo',
        description='Convert a GeoGebra construction (.ggb) into an image, '
                    'vector figure or animation.',
    )
    parser.add_argument('ggbfile', nargs='?', default=None,
                        help='GeoGebra file to convert')
    parser.add_argument('--ai-guide', action='store_true',
                        help='print the packaged AI agent usage guide '
                             '(AI_USAGE_PROMPT.md) and exit')
    parser.add_argument('-o', '--output', type=str, default=None,
                        help='output file (default: <ggbfile>.<ext>); '
                             'the extension can imply --format')
    parser.add_argument('-f', '--format', default=None,
                        choices=ALL_FORMATS,
                        help='export format (default: inferred from -o, else svg). '
                             'static vector: svg/pdf/eps/tikz; '
                             'render: png/gif/mp4/webm/mov')
    parser.add_argument('--standalone', action='store_true',
                        help='tikz: wrap in a compilable standalone document')
    parser.add_argument('--dpi', type=float, default=96.0,
                        help='pdf/eps: pixels-per-inch for the physical size (default: 96)')
    parser.add_argument('--keyframes', type=str, default=None,
                        help='render formats: JSON keyframes file to animate '
                             '(see keyframes docs)')
    parser.add_argument('--fps', type=float, default=None,
                        help='render formats: frames per second')
    parser.add_argument('--transparent', action='store_true',
                        help='render formats: transparent background '
                             '(png/webm/mov; gif is 1-bit)')
    parser.add_argument('--quality', default=None,
                        choices=['l', 'm', 'h', 'p', 'k'],
                        help='render formats: manim quality preset '
                             '(l=480p15 m=720p30 h=1080p60 p=1440p60 k=2160p60); '
                             'governs render-track resolution/fps (not vector size)')
    parser.add_argument('--reference-size', nargs=2, default=None,
                        help='reference/style canvas width and height in px')
    parser.add_argument('--export-size', nargs=2, default=['640', '480'],
                        help='final export canvas width and height in px (num or "auto")')
    parser.add_argument('--fit', default='contain',
                        choices=['contain', 'cover', 'width', 'height', 'none', 'manual'],
                        help='how to place the reference canvas inside export-size')
    parser.add_argument('--source-rect', default='source_view',
                        choices=['source_view', 'ggb_view', 'rendered_bounds'],
                        help='source rectangle placed into the reference canvas')
    parser.add_argument('--export-scale', type=float, default=None,
                        help='manual scale for --fit manual')
    parser.add_argument('--anchor', default='center',
                        choices=[
                            'top_left', 'top', 'top_right', 'left', 'center',
                            'right', 'bottom_left', 'bottom', 'bottom_right',
                        ],
                        help='anchor for the placed reference canvas')
    parser.add_argument('--offset', nargs=2, default=None,
                        help='x y offset in export pixels after anchoring')
    parser.add_argument('--bounds-padding', type=float, default=0,
                        help='padding in source pixels for --source-rect rendered_bounds')
    parser.add_argument('--infinite-policy', default='ignore',
                        choices=['clip', 'ignore'],
                        help='how rendered_bounds treats Line/Ray objects')
    parser.add_argument('-s', '--style', type=str, default=None,
                        help='style JSON file or packaged preset name '
                             '(default, book_blue, book_green, book_purple, book_red)')
    parser.add_argument('--log-level', type=str, default='WARNING',
                        choices=LOG_LEVELS,
                        help='logging level (default: WARNING)')
    parser.add_argument('-v', '--verbose', action='store_true',
                        help='alias for --log-level DEBUG')
    parser.add_argument('-q', '--quiet', action='store_true',
                        help='alias for --log-level CRITICAL (errors only)')

    args = parser.parse_args()

    if args.ai_guide:
        guide = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             'AI_USAGE_PROMPT.md')
        with open(guide, encoding='utf-8') as fh:
            sys.stdout.write(fh.read())
        return

    if args.ggbfile is None:
        parser.error('ggbfile is required (or use --ai-guide)')

    # Resolve logging level from mutually-supportive flags
    level = args.log_level
    if args.verbose:
        level = 'DEBUG'
    elif args.quiet:
        level = 'CRITICAL'
    configure_logging(level=level)

    ggbfile = os.path.abspath(args.ggbfile)
    if not os.path.isfile(ggbfile):
        logger.error('ggb file not found: %s', args.ggbfile)
        return 2

    style_path = _resolve_style_arg(args.style)
    if style_path is None:
        logger.error('style file not found: %s', args.style)
        return 2

    keyframes_path = ''
    if args.keyframes:
        keyframes_path = os.path.abspath(args.keyframes)
        if not os.path.isfile(keyframes_path):
            logger.error('keyframes file not found: %s', args.keyframes)
            return 2

    fmt = _resolve_format(args)
    ext = EXT_BY_FORMAT[fmt]
    output = os.path.abspath(args.output) if args.output else ggbfile[:-4] + ext

    reference_size = _parse_size(args.reference_size)
    export_size = _parse_size(args.export_size)
    export_offset = _parse_float_pair(args.offset)
    reference = (
        {'size': {'width': reference_size[0], 'height': reference_size[1]}}
        if reference_size is not None else None
    )
    content = {
        'source': args.source_rect,
        'padding': args.bounds_padding,
        'infinite_policy': args.infinite_policy,
    }
    export = {
        'size': {'width': export_size[0], 'height': export_size[1]},
        'fit': args.fit,
        'scale': args.export_scale,
        'anchor': args.anchor,
        'offset': export_offset,
    }

    logger.debug('FROM:   %s', ggbfile)
    logger.debug('TO:     %s', output)
    logger.debug('FORMAT: %s', fmt)
    logger.debug('REF:    %s', reference_size or '(source view)')
    logger.debug('EXPORT: %s', export_size)
    logger.debug('STYLE:  %s', style_path or '(none)')

    debug = bool(args.verbose or level == 'DEBUG')
    is_render = fmt in RENDER_FORMATS

    # Private temp dir — no cwd pollution, no cross-user races, auto-cleanup.
    with tempfile.TemporaryDirectory(prefix='animageo_') as tmp:
        driver = os.path.join(tmp, 'driver.py')

        if is_render:
            if keyframes_path:
                play_call = (
                    "with open({kf!r}) as _kf:\n"
                    "            self.play_keyframes(json.load(_kf))"
                ).format(kf=keyframes_path)
            else:
                logger.info('no --keyframes given: rendering a single frame')
                play_call = "pass"
            with open(driver, 'w', encoding='utf-8') as f:
                f.write(_RENDER_DRIVER_TEMPLATE.format(
                    ggbfile=ggbfile, style=style_path, reference=reference,
                    content=content, export=export, debug=debug,
                    play_call=play_call,
                ))

            media_dir = os.path.join(tmp, 'media')
            manim_args = ['manim', driver, 'Scene_', '--format', fmt,
                          '--media_dir', media_dir]
            if fmt == 'png' and not keyframes_path:
                manim_args.append('-s')  # save last frame as a PNG
            if args.quality:
                manim_args += ['-q', args.quality]
            if args.fps:
                manim_args += ['--fps', str(args.fps)]
            if args.transparent:
                manim_args.append('--transparent')

            logger.info('Running manim... [first run may take longer]')
            try:
                subprocess.run(manim_args, check=True, env=_manim_env())
            except FileNotFoundError:
                logger.error('manim executable not found on PATH')
                return 127
            except subprocess.CalledProcessError as e:
                logger.error('manim failed with exit code %d', e.returncode)
                return e.returncode

            produced = _find_rendered_file(media_dir, ext)
            if produced is None:
                logger.error('manim did not produce a %s file', fmt)
                return 1
            os.makedirs(os.path.dirname(output) or '.', exist_ok=True)
            shutil.move(produced, output)

        else:
            if fmt == 'tikz':
                export_call = 'self.exportTikZ({output!r}, standalone={standalone!r})'.format(
                    output=output, standalone=bool(args.standalone))
            elif fmt == 'pdf':
                export_call = 'self.exportPDF({output!r}, dpi={dpi!r})'.format(
                    output=output, dpi=float(args.dpi))
            elif fmt == 'eps':
                export_call = 'self.exportEPS({output!r}, dpi={dpi!r})'.format(
                    output=output, dpi=float(args.dpi))
            elif fmt == 'jsxgraph':
                # Pick the JSXGraph output mode from the -o extension:
                # .json → declarative spec (animageo-board/v1), .js → board
                # fragment, anything else → self-contained html.
                jsx_ext = os.path.splitext(output)[1].lower()
                jsx_out = {'.json': 'spec', '.js': 'js'}.get(jsx_ext, 'html')
                export_call = 'self.exportJSXGraph({output!r}, output={jsx_out!r})'.format(
                    output=output, jsx_out=jsx_out)
            else:  # svg
                export_call = 'self.exportSVG({output!r})'.format(output=output)

            with open(driver, 'w', encoding='utf-8') as f:
                f.write(_DRIVER_TEMPLATE.format(
                    ggbfile=ggbfile, style=style_path, reference=reference,
                    content=content, export=export, debug=debug,
                    export_call=export_call,
                ))

            logger.info('Running manim... [first run may take longer]')
            try:
                subprocess.run(['manim', driver, 'Scene_'], check=True, env=_manim_env())
            except FileNotFoundError:
                logger.error('manim executable not found on PATH')
                return 127
            except subprocess.CalledProcessError as e:
                logger.error('manim failed with exit code %d', e.returncode)
                return e.returncode

    logger.info("%s file exported: '%s'", fmt.upper(), output)
    return 0


if __name__ == '__main__':
    sys.exit(main())
