"""Convenience super-module for the AnimaGeo DSL.

``from animageo.dsl import *`` — one-stop shop that re-exports every
factory (``Point``, ``Circle``, ``Midpoint``, …) and every proxy type
(``PointProxy``, ``CircleProxy``, ``StyleProxy``, …) in a single
import. Intended for **IDE autocomplete only** — at runtime, the DSL
transform drops all top-level imports, and names resolve through the
exec namespace instead. So this module is safe to star-import in a
DSL script:

    # scene10.py — one-line IDE stubs, zero runtime import
    from animageo.dsl import *

    deg = 3.141592653589793238462 / 180
    B = Rotate(R, x * deg, Q)

For named elements loaded by ``loadGGB`` (``R``, ``Q`` above), the
recommended pattern is to additionally import a companion stub file
(typically auto-generated by ``loadGGB`` in a future phase)::

    from animageo.dsl import *
    from scene10_stubs import *   # R: PointProxy, Q: PointProxy, …
"""

from __future__ import annotations

# Factories — every auto-discovered command, pre-populated as
# module-level attributes by ``namespace.py``.
from .parsers.dsl.namespace import *  # noqa: F401,F403

# Helpers (style/hide/show) and the math bundle.
from .parsers.dsl.namespace import style, hide, show  # noqa: F401

# Proxy types — for declaring ``R: PointProxy`` etc.
# These exist at runtime as ``ElementProxy`` (single class), but the
# ``.pyi`` stub declares them as separate types so IDEs can narrow
# the return type of each factory.
from .parsers.dsl.proxy import ElementProxy  # noqa: F401

# StyleProxy — for ``.style.stroke = '#f00'`` patterns.
from .style.proxy import StyleProxy  # noqa: F401
