#!/usr/bin/env python3
"""Regression corpus of the classic renderer: .ggb drawings, DSL and animations.

    python scripts/classic_corpus.py record  [CORPUS] [-m manifest.json]
    python scripts/classic_corpus.py verify  [CORPUS] [-m manifest.json]
    python scripts/classic_corpus.py compare [CORPUS] --base OLD_CHECKOUT [--md report.md]

``CORPUS`` is a directory (searched recursively; default: the environment
variable ``ANIMAGEO_CORPUS``). The corpus files stay outside the repository:
only this runner and the numbers it prints are kept here. A scene is

- ``x.ggb`` — the drawing alone: ``loadGGB(x, generate_stubs=False)`` →
  ``exportSVG`` (the classic path of the web service);
- ``x.dsl`` next to ``x.ggb`` — a DSL block over the drawing, as the web
  runs it: ``loadGGB`` → ``putCode(block)`` → the new elements are drawn →
  ``exportSVG``;
- ``x.py`` — a DSL scene alone: ``loadCode(x.py)`` → ``exportSVG``;
- ``x.animation.json`` next to ``x.ggb`` — a timeline of the web
  (``{fps, resolution, timeline}``): the scene code is generated by the web
  service (``app/services/animation_export.py`` of the checkout given with
  ``--web`` or ``ANIMAGEO_WEB``), manim renders its last frame (PNG,
  ``-ql -s``) and, for the first ``--video N`` animations, a short low
  quality video (compared frame by frame). Without a web checkout the
  animations are skipped.

Files and directories whose name starts with ``_`` or ``.`` are skipped.
Every scene renders in a fresh subprocess of this interpreter with
``PYTHONPATH`` set to the library checkout (and the web checkout for
animations); the subprocess reports the time of ``import``, ``loadGGB``, the
code and the export.

``record`` writes ``{format, animageo, manim, python, files: {path:
"sha256:…"}}``; ``verify`` renders again and lists every scene whose hash
differs, that failed or that is missing on either side (exit 1).
``compare --base`` renders every scene with an older checkout of the library
and with this one, and sorts the pairs: ``same`` (byte for byte),
``same-normalized`` (an SVG equal after numbers are rounded and ids
renumbered, a PNG with equal pixels, a video with equal frames),
``different``, ``failed-both`` (an old failure kept), ``fixed`` (failed
before, renders now) and ``broken`` (rendered before, fails now); it exits 1
on ``different`` or ``broken``. ``--keep DIR`` keeps the outputs.

``--diffs FILE`` (``verify`` and ``compare``; default
``docs/native/classic-diffs.json``) lists the intended differences of the
classic renderer: ``{format, diffs: {scene id: {item, changelog}}}`` — the
scene, the item of the kernel spec §15 that changed it and its line of the
CHANGELOG. A listed scene that changed is ``expected``, not a failure; a
listed scene that did not change is reported, so the list stays true.

The plan for 1.8.0a1 asks for at least 30 ``.ggb`` and 20 DSL scenes; a
smaller corpus is reported, not refused. Needs manim (and cairo) on the
machine; this script itself only starts subprocesses and does not import
manim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import re
import shutil
import statistics
import subprocess
import sys
import tempfile
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FORMAT = 'animageo-classic-corpus/v1'
MIN_GGB = 30
MIN_DSL = 20
KINDS = ('ggb', 'dsl-block', 'dsl-file', 'animation')
OUTPUT_SUFFIX = {'ggb': '.svg', 'dsl-block': '.svg', 'dsl-file': '.svg', 'animation': '.png'}
ANIMATION_CONFIG = {'pixel_width': 480, 'pixel_height': 270, 'frame_rate': 15}
VIDEO_CONFIG = {'pixel_width': 256, 'pixel_height': 144, 'frame_rate': 10}
TIMINGS = ('import', 'load', 'code', 'export', 'scene', 'render', 'video', 'total')
DIFFS_FORMAT = 'animageo-classic-diffs/v1'
DIFFS_PATH = REPO_ROOT / 'docs' / 'native' / 'classic-diffs.json'

# Runs in the subprocess, with the library of one checkout on PYTHONPATH.
# The job comes as a JSON file (a .ggb in sys.argv made the 1.10 package
# skip its classic import, see the CHANGELOG of 1.11.0rc1).
_WORKER = r'''# generated by scripts/classic_corpus.py
import json, os, subprocess, sys, time, traceback
from pathlib import Path

job = json.loads(Path(sys.argv[1]).read_text(encoding='utf-8'))
times = {}
result = {'ok': False, 'times': times}
start = time.perf_counter()


def lap(name, since):
    now = time.perf_counter()
    times[name] = round(now - since, 6)
    return now


def draw_new_elements(scene):
    """What the web does after a DSL block (add_missing_geometry)."""
    if hasattr(scene, 'applyOverlay'):
        scene.applyOverlay()
    existing = {getattr(m, 'name', None) for m in scene.mobjects if getattr(m, 'name', None)}
    for elem in scene.geo.elements:
        if elem.name not in existing:
            scene.addGeoElement(elem)
            existing.add(elem.name)
    scene.updateAllGeometry()


def manim(scene_file, media, extra):
    cmd = [sys.executable, '-m', 'manim', 'render', '-ql', '--disable_caching', *extra,
           str(scene_file), 'AnimScene', '--media_dir', str(media)]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=job['timeout'], check=False)
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or '').strip().splitlines()[-8:]
        raise RuntimeError(f'manim exit {proc.returncode}: ' + ' | '.join(tail))


try:
    kind, out = job['kind'], Path(job['out'])
    if kind == 'animation':
        sys.path.insert(0, job['web'])
        from app.services.animation_export import _generate_animation_scene
        t = lap('import', start)
        data = json.loads(Path(job['code']).read_text(encoding='utf-8'))
        code = _generate_animation_scene(ggb_path=job['ggb'], style_path=None, config=None,
                                         timeline=data['timeline'],
                                         manim_config_override=job['frame'])
        scene_file = out.with_name(out.stem + '.scene.py')
        scene_file.write_text(code, encoding='utf-8')
        t = lap('scene', t)
        media = out.with_name(out.stem + '.media')
        manim(scene_file, media, ['-s', '--format', 'png'])
        pngs = sorted(p for p in (media / 'images').rglob('*.png'))
        if not pngs:
            raise RuntimeError('manim wrote no last frame')
        os.replace(pngs[-1], out)
        t = lap('render', t)
        if job.get('video'):
            code = _generate_animation_scene(ggb_path=job['ggb'], style_path=None, config=None,
                                             timeline=data['timeline'],
                                             manim_config_override=job['video'])
            scene_file.write_text(code, encoding='utf-8')
            manim(scene_file, media, ['--format', 'mp4'])
            videos = sorted((media / 'videos').rglob('AnimScene.mp4'))
            if not videos:
                raise RuntimeError('manim wrote no video')
            os.replace(videos[-1], out.with_suffix('.mp4'))
            t = lap('video', t)
    else:
        from animageo import AnimaGeoScene
        t = lap('import', start)
        scene = AnimaGeoScene()
        if kind in ('ggb', 'dsl-block'):
            scene.loadGGB(job['ggb'], generate_stubs=False)
            t = lap('load', t)
        if kind == 'dsl-block':
            block = Path(job['code']).read_text(encoding='utf-8').strip()
            if block:
                scene.putCode(block)
                draw_new_elements(scene)
            t = lap('code', t)
        if kind == 'dsl-file':
            scene.loadCode(job['code'])
            t = lap('code', t)
        scene.exportSVG(str(out))
        t = lap('export', t)
    result['ok'] = out.is_file()
    if not result['ok']:
        result['error'] = 'no output'
except BaseException as exc:                       # noqa: BLE001  (reported, not raised)
    tail = traceback.format_exc().strip().splitlines()[-3:]
    result['error'] = f'{type(exc).__name__}: {exc}'[:500]
    result['trace'] = tail
times['total'] = round(time.perf_counter() - start, 6)
Path(job['result']).write_text(json.dumps(result), encoding='utf-8')
'''


@dataclass(frozen=True)
class Scene:
    """One scene of the corpus: ``id`` is the path of its main file, relative to the corpus."""
    id: str
    kind: str
    ggb: Path | None = None
    code: Path | None = None


def _skipped(rel: Path) -> bool:
    return any(part.startswith(('_', '.')) for part in rel.parts)


def corpus_scenes(root: Path) -> list:
    """Every scene under ``root`` (see the module doc), sorted by id."""
    out = []
    for path in sorted(root.rglob('*')):
        rel = path.relative_to(root)
        if not path.is_file() or _skipped(rel):
            continue
        name = path.name
        if path.suffix == '.ggb':
            out.append(Scene(rel.as_posix(), 'ggb', ggb=path))
        elif path.suffix == '.py':
            out.append(Scene(rel.as_posix(), 'dsl-file', code=path))
        elif path.suffix == '.dsl' and path.with_suffix('.ggb').is_file():
            out.append(Scene(rel.as_posix(), 'dsl-block', ggb=path.with_suffix('.ggb'), code=path))
        elif name.endswith('.animation.json'):
            ggb = path.with_name(name[:-len('.animation.json')] + '.ggb')
            if ggb.is_file():
                out.append(Scene(rel.as_posix(), 'animation', ggb=ggb, code=path))
    return sorted(out, key=lambda s: s.id)


def counts(scenes) -> dict:
    out = {kind: 0 for kind in KINDS}
    for scene in scenes:
        out[scene.kind] += 1
    return out


# --- comparing outputs ------------------------------------------------------

_NUMBER = re.compile(r'-?\d+\.\d+(?:e-?\d+)?')
_ID_DEF = re.compile(r'\bid="([^"]+)"')


def normalize_svg(text: str, digits: int = 3) -> str:
    """An SVG with numbers rounded to ``digits`` decimals and ids renumbered.

    Cairo numbers glyphs, clips and surfaces by the order it meets them; two
    renders of one drawing that differ only there (or in the last digits of
    a coordinate) normalize to the same text.
    """
    def number(match):
        value = round(float(match.group(0)), digits)
        return f'{0.0 if value == 0 else value:.{digits}f}'

    text = _NUMBER.sub(number, text)
    names = {}
    for match in _ID_DEF.finditer(text):
        names.setdefault(match.group(1), f'id{len(names)}')
    if names:
        pattern = re.compile(r'(?<=["#(])(' + '|'.join(re.escape(n) for n in sorted(names, key=len, reverse=True))
                             + r')(?=["),])')
        text = pattern.sub(lambda m: names[m.group(1)], text)
    return text


def _first_difference(a: str, b: str) -> str:
    la, lb = a.splitlines(), b.splitlines()
    for i, (x, y) in enumerate(zip(la, lb), 1):
        if x != y:
            return f'line {i}: {x.strip()[:120]!r} → {y.strip()[:120]!r}'
    return f'{len(la)} lines → {len(lb)} lines'


def _png_pixels(path: Path):
    try:
        from PIL import Image
    except ImportError:                           # pragma: no cover - PIL comes with manim
        return None
    with Image.open(path) as image:
        return image.size, image.convert('RGBA').tobytes()


def video_frames_digest(path: Path) -> str | None:
    """sha256 of the decoded frames (rgb24), or ``None`` without ffmpeg."""
    if shutil.which('ffmpeg') is None:
        return None
    proc = subprocess.run(['ffmpeg', '-v', 'error', '-i', str(path), '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'],
                          capture_output=True, check=False)
    if proc.returncode != 0:
        return None
    return hashlib.sha256(proc.stdout).hexdigest()


def compare_outputs(old: Path, new: Path) -> tuple:
    """``(verdict, detail)`` for two outputs of one scene: ``same``, ``same-normalized`` or ``different``."""
    a, b = old.read_bytes(), new.read_bytes()
    if a == b:
        return 'same', ''
    if old.suffix == '.svg':
        ta, tb = normalize_svg(a.decode('utf-8')), normalize_svg(b.decode('utf-8'))
        if ta == tb:
            return 'same-normalized', 'numbers or ids'
        return 'different', _first_difference(ta, tb)
    if old.suffix == '.png':
        pa, pb = _png_pixels(old), _png_pixels(new)
        if pa is not None and pa == pb:
            return 'same-normalized', 'equal pixels'
        if pa is not None and pa[0] == pb[0]:
            changed = sum(1 for i in range(0, len(pa[1]), 4) if pa[1][i:i + 4] != pb[1][i:i + 4])
            return 'different', f'{changed} of {pa[0][0] * pa[0][1]} pixels'
        return 'different', f'size {pa and pa[0]} → {pb and pb[0]}'
    if old.suffix == '.mp4':
        da, db = video_frames_digest(old), video_frames_digest(new)
        if da is not None and da == db:
            return 'same-normalized', 'equal frames'
        return 'different', 'frames differ' if da and db else 'cannot decode'
    return 'different', f'{len(a)} → {len(b)} bytes'


def classify(old: dict, new: dict, verdict: str | None) -> str:
    """The verdict of a pair of runs (``{ok, error}``) — see ``compare`` in the module doc."""
    if old['ok'] and new['ok']:
        return verdict or 'different'
    if not old['ok'] and not new['ok']:
        return 'failed-both'
    return 'fixed' if new['ok'] else 'broken'


def load_diffs(path: Path | None) -> dict:
    """``{scene id: {item, changelog}}`` of a classic-diffs file (``{}`` without one)."""
    if path is None or not Path(path).is_file():
        return {}
    data = json.loads(Path(path).read_text(encoding='utf-8'))
    if data.get('format') != DIFFS_FORMAT:
        raise ValueError(f'{path}: not an {DIFFS_FORMAT} file')
    for scene, why in data.get('diffs', {}).items():
        if not (isinstance(why, dict) and why.get('item') and why.get('changelog')):
            raise ValueError(f'{path}: {scene} needs "item" and "changelog"')
    return dict(data.get('diffs', {}))


def apply_diffs(verdict: str, scene_id: str, diffs: dict) -> str:
    """``expected`` for a listed scene that changed; ``unchanged-listed`` for a listed one that did not."""
    if scene_id not in diffs:
        return verdict
    if verdict in ('different', 'broken', 'fixed'):
        return 'expected'
    if verdict in ('same', 'same-normalized'):
        return 'unchanged-listed'
    return verdict


# --- running ----------------------------------------------------------------

class Runner:
    """Renders scenes with one library checkout; one work directory per thread.

    The work directory (manim's ``media/Tex``, the web's LaTeX cache) lives as
    long as the runner, so labels compile once per thread — for every
    checkout alike, which keeps their timings comparable.
    """

    def __init__(self, library: Path, *, web: Path | None, timeout: float, root: Path, label: str):
        self.library, self.web, self.timeout = Path(library).resolve(), web, timeout
        self.root, self.label = root, label
        self._local = threading.local()

    def _workdir(self) -> Path:
        path = getattr(self._local, 'path', None)
        if path is None:
            path = Path(tempfile.mkdtemp(prefix=f'{self.label}-', dir=self.root))
            (path / '_worker.py').write_text(_WORKER, encoding='utf-8')
            self._local.path = path
        return path

    def env(self) -> dict:
        env = os.environ.copy()
        paths = [str(self.library)] + ([str(self.web)] if self.web else [])
        existing = env.get('PYTHONPATH', '')
        env['PYTHONPATH'] = os.pathsep.join(paths + ([existing] if existing else []))
        env['TEX_CACHE_DIR'] = str(self._workdir() / 'web-tex-cache')
        return env

    def render(self, scene: Scene, *, video: bool = False) -> tuple:
        """``(result, output path or None)``; ``result`` is ``{ok, error?, times}``."""
        work = self._workdir()
        stem = hashlib.sha256(scene.id.encode()).hexdigest()[:16]
        out = work / (stem + OUTPUT_SUFFIX[scene.kind])
        for stale in work.glob(stem + '*'):
            if stale.is_dir():
                shutil.rmtree(stale, ignore_errors=True)
            else:
                stale.unlink()
        if scene.kind == 'animation' and self.web is None:
            return {'ok': False, 'skipped': True, 'error': 'needs --web (ANIMAGEO_WEB)', 'times': {}}, None
        job = {'kind': scene.kind, 'ggb': str(scene.ggb) if scene.ggb else None,
               'code': str(scene.code) if scene.code else None, 'out': str(out),
               'result': str(work / (stem + '.result.json')), 'web': str(self.web) if self.web else None,
               'frame': ANIMATION_CONFIG, 'video': VIDEO_CONFIG if video else None, 'timeout': self.timeout}
        job_path = work / (stem + '.job.json')
        job_path.write_text(json.dumps(job), encoding='utf-8')
        try:
            proc = subprocess.run([sys.executable, str(work / '_worker.py'), str(job_path)], cwd=work,
                                  env=self.env(), capture_output=True, text=True,
                                  timeout=self.timeout * (3 if video else 2), check=False)
        except subprocess.TimeoutExpired:
            return {'ok': False, 'error': f'timed out after {self.timeout:g} s', 'times': {}}, None
        result_path = Path(job['result'])
        if not result_path.is_file():
            tail = (proc.stderr or proc.stdout or '').strip().splitlines()[-5:]
            return {'ok': False, 'error': f'worker exit {proc.returncode}: ' + ' | '.join(tail), 'times': {}}, None
        result = json.loads(result_path.read_text(encoding='utf-8'))
        return result, (out if result.get('ok') else None)


def _keep(keep: Path | None, label: str, scene: Scene, output: Path | None) -> None:
    if keep is None or output is None:
        return
    for path in [output] + [p for p in [output.with_suffix('.mp4')] if p.is_file()]:
        target = keep / label / (scene.id + path.suffix)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, target)


def _subprocess_line(code: str, library: Path) -> str:
    env = os.environ.copy()
    env['PYTHONPATH'] = str(library) + (os.pathsep + env['PYTHONPATH'] if env.get('PYTHONPATH') else '')
    proc = subprocess.run([sys.executable, '-c', code], capture_output=True, text=True, env=env,
                          cwd=tempfile.gettempdir(), check=False)
    return proc.stdout.strip() or '?'


def library_version(library: Path = REPO_ROOT) -> str:
    return _subprocess_line('import animageo; print(animageo.__version__)', library)


def manim_version() -> str:
    return _subprocess_line('import manim; print(manim.__version__)', REPO_ROOT)


def sha256_file(path: Path) -> str:
    return 'sha256:' + hashlib.sha256(path.read_bytes()).hexdigest()


def _corpus(args) -> Path | None:
    corpus = args.corpus or os.environ.get('ANIMAGEO_CORPUS')
    return Path(corpus).resolve() if corpus else None


def _web(args) -> Path | None:
    web = args.web or os.environ.get('ANIMAGEO_WEB')
    return Path(web).resolve() if web else None


def _selected(args, root: Path) -> list:
    scenes = corpus_scenes(root)
    if args.only:
        kinds = set(args.only.split(','))
        scenes = [s for s in scenes if s.kind in kinds]
    if args.limit:
        scenes = scenes[:args.limit]
    return scenes


def _report_size(scenes) -> None:
    n = counts(scenes)
    print('corpus: ' + ', '.join(f'{v} {k}' for k, v in n.items()))
    dsl = n['dsl-block'] + n['dsl-file']
    if n['ggb'] < MIN_GGB or dsl < MIN_DSL:
        print(f'note: the release check asks for at least {MIN_GGB} .ggb and {MIN_DSL} DSL scenes')


def hash_corpus(scenes, *, runner: Runner, keep: Path | None, jobs: int) -> tuple:
    """``({id: hash}, {id: error}, {id: skipped reason})`` for the scenes."""
    hashes, errors, skipped = {}, {}, {}
    lock = threading.Lock()

    def one(item):
        i, scene = item
        result, output = runner.render(scene)
        with lock:
            print(f'[{i}/{len(scenes)}] {scene.id}' + ('' if result['ok'] else f"  — {result['error']}"), flush=True)
            if result.get('skipped'):
                skipped[scene.id] = result['error']
            elif output is None:
                errors[scene.id] = result['error']
            else:
                hashes[scene.id] = sha256_file(output)
                _keep(keep, runner.label, scene, output)

    with ThreadPoolExecutor(max_workers=max(1, jobs)) as pool:
        list(pool.map(one, enumerate(scenes, 1)))
    return hashes, errors, skipped


def cmd_record(args) -> int:
    root = _corpus(args)
    if root is None:
        print('no corpus: pass its directory or set ANIMAGEO_CORPUS')
        return 2
    with tempfile.TemporaryDirectory(prefix='animageo-corpus-') as tmp:
        runner = Runner(REPO_ROOT, web=_web(args), timeout=args.timeout, root=Path(tmp), label='head')
        hashes, errors, skipped = hash_corpus(_selected(args, root), runner=runner, keep=args.keep, jobs=args.jobs)
    for rel, why in sorted(skipped.items()):
        print(f'skipped: {rel}: {why}')
    if errors:
        for rel, error in sorted(errors.items()):
            print(f'not recorded: {rel}: {error}')
        print(f'{len(errors)} scenes failed to render; manifest not written')
        return 1
    manifest = {'format': FORMAT, 'animageo': library_version(), 'manim': manim_version(),
                'python': platform.python_version(), 'files': dict(sorted(hashes.items()))}
    path = Path(args.manifest) if args.manifest else root / 'manifest.json'
    path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    _report_size([s for s in corpus_scenes(root) if s.id in hashes])
    print(f'wrote {path} ({len(hashes)} scenes)')
    return 0


def cmd_verify(args) -> int:
    root = _corpus(args)
    if root is None:
        print('no corpus: pass its directory or set ANIMAGEO_CORPUS')
        return 2
    path = Path(args.manifest) if args.manifest else root / 'manifest.json'
    try:
        manifest = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError) as exc:
        print(f'cannot read {path}: {exc}')
        return 2
    if manifest.get('format') != FORMAT:
        print(f'{path}: not an {FORMAT} manifest')
        return 2
    expected = manifest.get('files', {})
    diffs = load_diffs(args.diffs)
    with tempfile.TemporaryDirectory(prefix='animageo-corpus-') as tmp:
        runner = Runner(REPO_ROOT, web=_web(args), timeout=args.timeout, root=Path(tmp), label='head')
        hashes, errors, skipped = hash_corpus(_selected(args, root), runner=runner, keep=args.keep, jobs=args.jobs)
    problems = []
    for rel in sorted(set(expected) | set(hashes) | set(errors)):
        if rel in skipped:
            continue
        if rel in errors:
            problems.append(f'failed: {rel}: {errors[rel]}')
        elif rel not in expected:
            problems.append(f'not in the manifest: {rel}')
        elif rel not in hashes:
            problems.append(f'missing from the corpus: {rel}')
        elif hashes[rel] != expected[rel]:
            if rel in diffs:
                print(f"expected: {rel}: {diffs[rel]['item']}")
            else:
                problems.append(f'changed: {rel}')
        elif rel in diffs:
            print(f'listed in {args.diffs} but unchanged: {rel}')
    for line in problems:
        print(line)
    print(f"recorded with animageo {manifest.get('animageo')}, manim {manifest.get('manim')}; "
          f'now animageo {library_version()}, manim {manim_version()}')
    print(f'{len(expected)} scenes, {len(problems)} differences, {len(skipped)} skipped')
    return 1 if problems else 0


# --- compare ----------------------------------------------------------------

def _stats(values) -> dict:
    values = sorted(v for v in values if v is not None)
    if not values:
        return {}
    p95 = values[min(len(values) - 1, max(0, round(0.95 * len(values)) - 1))]
    return {'n': len(values), 'median': round(statistics.median(values), 4), 'p95': round(p95, 4),
            'sum': round(sum(values), 3)}


def summarize(rows, *, base: str, head: str) -> dict:
    """The report of ``compare`` from its rows (``{id, kind, verdict, detail, base, head}``)."""
    verdicts = {}
    for row in rows:
        verdicts.setdefault(row['kind'], {}).setdefault(row['verdict'], 0)
        verdicts[row['kind']][row['verdict']] += 1
    timings = {}
    for kind in KINDS:
        both = [r for r in rows if r['kind'] == kind and r['base']['ok'] and r['head']['ok']]
        if not both:
            continue
        timings[kind] = {name: {'base': _stats(r['base']['times'].get(name) for r in both),
                                'head': _stats(r['head']['times'].get(name) for r in both)}
                         for name in TIMINGS if any(name in r['base']['times'] for r in both)}
    notable = [r for r in rows if r['verdict'] not in ('same', 'same-normalized', 'skipped')]
    return {'base': base, 'head': head, 'scenes': len(rows), 'verdicts': verdicts, 'timings': timings,
            'notable': [{k: r[k] for k in ('id', 'kind', 'verdict', 'detail')}
                        | {'base_error': r['base'].get('error'), 'head_error': r['head'].get('error')}
                        for r in notable]}


def markdown(report: dict) -> str:
    lines = [f"# Corpus: {report['base']} → {report['head']}", '',
             f"{report['scenes']} scenes.", '', '| kind | verdicts |', '|---|---|']
    for kind, verdicts in sorted(report['verdicts'].items()):
        lines.append(f'| {kind} | ' + ', '.join(f'{v} {k}' for k, v in sorted(verdicts.items())) + ' |')
    lines += ['', '## Time, s (median / p95; both checkouts on the same scenes)', '',
              '| kind | step | base | head |', '|---|---|---|---|']
    for kind, steps in report['timings'].items():
        for step, sides in steps.items():
            b, h = sides['base'], sides['head']
            if b and h:
                lines.append(f"| {kind} | {step} | {b['median']} / {b['p95']} | {h['median']} / {h['p95']} |")
    lines += ['', '## Not the same', '']
    if not report['notable']:
        lines.append('none')
    for row in report['notable']:
        why = row['detail'] or row['head_error'] or row['base_error'] or ''
        lines.append(f"- `{row['id']}` ({row['kind']}): **{row['verdict']}** {why}".rstrip())
    return '\n'.join(lines) + '\n'


def cmd_compare(args) -> int:
    root = _corpus(args)
    if root is None:
        print('no corpus: pass its directory or set ANIMAGEO_CORPUS')
        return 2
    base_lib, web = Path(args.base).resolve(), _web(args)
    diffs = load_diffs(args.diffs)
    scenes = _selected(args, root)
    _report_size(scenes)
    animations = [s.id for s in scenes if s.kind == 'animation'][:args.video]
    rows, lock = [], threading.Lock()
    with tempfile.TemporaryDirectory(prefix='animageo-corpus-') as tmp:
        base = Runner(base_lib, web=web, timeout=args.timeout, root=Path(tmp), label='base')
        head = Runner(REPO_ROOT, web=web, timeout=args.timeout, root=Path(tmp), label='head')

        def one(item):
            i, scene = item
            video = scene.id in animations
            r_base, out_base = base.render(scene, video=video)
            r_head, out_head = head.render(scene, video=video)
            verdict = detail = None
            if r_base.get('skipped'):
                verdict, detail = 'skipped', r_base['error']
            elif out_base is not None and out_head is not None:
                verdict, detail = compare_outputs(out_base, out_head)
                vb, vh = out_base.with_suffix('.mp4'), out_head.with_suffix('.mp4')
                if verdict != 'different' and vb.is_file() and vh.is_file():
                    v_verdict, v_detail = compare_outputs(vb, vh)
                    if v_verdict == 'different':
                        verdict, detail = 'different', 'video: ' + v_detail
            row = {'id': scene.id, 'kind': scene.kind, 'base': r_base, 'head': r_head,
                   'verdict': verdict if verdict == 'skipped' else apply_diffs(
                       classify(r_base, r_head, verdict), scene.id, diffs),
                   'detail': detail or '', 'video': video}
            _keep(args.keep, 'base', scene, out_base)
            _keep(args.keep, 'head', scene, out_head)
            with lock:
                rows.append(row)
                print(f"[{len(rows)}/{len(scenes)}] {scene.id}: {row['verdict']} {row['detail']}".rstrip(), flush=True)

        with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
            list(pool.map(one, enumerate(scenes, 1)))
    rows.sort(key=lambda r: r['id'])
    report = summarize(rows, base=library_version(base_lib), head=library_version())
    if args.json:
        Path(args.json).write_text(json.dumps({'report': report, 'rows': rows}, ensure_ascii=False, indent=1) + '\n',
                                   encoding='utf-8')
    text = markdown(report)
    if args.md:
        Path(args.md).write_text(text, encoding='utf-8')
    print(text)
    bad = sum(1 for r in rows if r['verdict'] in ('different', 'broken', 'unchanged-listed'))
    return 1 if bad else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    sub = parser.add_subparsers(dest='command', required=True)
    for name, func, text in (('record', cmd_record, 'render the corpus and write the manifest'),
                             ('verify', cmd_verify, 'render the corpus and compare with the manifest'),
                             ('compare', cmd_compare, 'render the corpus with an older checkout and this one')):
        p = sub.add_parser(name, help=text)
        p.add_argument('corpus', nargs='?', help='corpus directory (default: $ANIMAGEO_CORPUS)')
        if name == 'compare':
            p.add_argument('--base', required=True, help='the older library checkout (its root directory)')
            p.add_argument('--json', help='write the rows and the report as JSON')
            p.add_argument('--md', help='write the report as Markdown')
            p.add_argument('--video', type=int, default=0, metavar='N',
                           help='also render a short video for the first N animations')
        else:
            p.add_argument('-m', '--manifest', help='manifest path (default: <corpus>/manifest.json)')
        if name != 'record':
            p.add_argument('--diffs', type=Path, default=DIFFS_PATH,
                           help='intended differences (default: docs/native/classic-diffs.json)')
        p.add_argument('--web', help='web service checkout for animations (default: $ANIMAGEO_WEB)')
        p.add_argument('--only', help='comma-separated kinds: ' + ','.join(KINDS))
        p.add_argument('--limit', type=int, help='the first N scenes only')
        p.add_argument('-j', '--jobs', type=int, default=1, help='scenes rendered at once (default 1)')
        p.add_argument('--keep', type=Path, help='keep the outputs in this directory')
        p.add_argument('--timeout', type=float, default=300.0, help='seconds per render (default 300)')
        p.set_defaults(func=func)
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if shutil.which('manim') is None and subprocess.run(
            [sys.executable, '-c', 'import manim'], capture_output=True, check=False).returncode != 0:
        print('manim is not installed (the classic renderer needs it)')
        return 2
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
