#!/usr/bin/env python3
"""Regression corpus of the classic renderer: SVG hashes of .ggb and DSL scenes.

    python scripts/classic_corpus.py record <corpus_dir> [-m manifest.json]
    python scripts/classic_corpus.py verify <corpus_dir> [-m manifest.json]

The corpus is a directory (searched recursively) of GeoGebra files ``*.ggb``
and DSL files ``*.py`` (code that ``AnimaGeoScene.loadCode`` reads; files
whose name starts with ``_`` are skipped). Every scene is rendered to SVG in a
fresh subprocess with the library of this checkout:

- ``.ggb`` — ``python -m animageo <file> -o <out>.svg`` (the classic CLI);
- DSL — a driver scene ``loadCode(<file>)`` + ``exportSVG(<out>)`` run by
  ``manim <driver> Scene_``.

``record`` writes ``{format, animageo, manim, python, files: {path:
"sha256:…"}}`` (paths relative to the corpus); ``verify`` renders again and
lists every file whose hash differs, that failed to render or that is missing
from either side, exiting 1 on any difference. ``--keep DIR`` keeps the SVGs
(e.g. to diff them). The plan for 1.8.0a1 asks for at least 30 ``.ggb`` and
20 DSL scenes; a smaller corpus is reported, not refused.

Needs manim (and cairo) on the machine that runs it; this script itself only
starts subprocesses and does not import manim.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
FORMAT = 'animageo-classic-corpus/v1'
MIN_GGB = 30
MIN_DSL = 20

_DSL_DRIVER = """\
# generated by scripts/classic_corpus.py
from animageo import AnimaGeoScene


class Scene_(AnimaGeoScene):
    def construct(self):
        self.loadCode({source!r})
        self.exportSVG({output!r})
"""


def _env() -> dict:
    env = os.environ.copy()
    existing = env.get('PYTHONPATH', '')
    env['PYTHONPATH'] = str(REPO_ROOT) + (os.pathsep + existing if existing else '')
    return env


def _library_version() -> str:
    proc = subprocess.run(
        [sys.executable, '-c', 'import animageo; print(animageo.__version__)'],
        capture_output=True, text=True, env=_env(), cwd=REPO_ROOT, check=False)
    return proc.stdout.strip() or '?'


def _manim_version() -> str:
    proc = subprocess.run(
        [sys.executable, '-c', 'import manim; print(manim.__version__)'],
        capture_output=True, text=True, env=_env(), check=False)
    return proc.stdout.strip() or '?'


def corpus_files(root: Path) -> list:
    """``.ggb`` and DSL ``.py`` files under ``root``, sorted by relative path."""
    out = []
    for path in sorted(root.rglob('*')):
        if not path.is_file() or path.name.startswith('_'):
            continue
        if path.suffix in ('.ggb', '.py'):
            out.append(path)
    return out


def render(source: Path, workdir: Path, timeout: float) -> Path:
    """Render ``source`` to SVG in ``workdir``; raise ``RuntimeError`` on failure."""
    output = workdir / 'out.svg'
    if source.suffix == '.ggb':
        cmd = [sys.executable, '-m', 'animageo', str(source), '-o', str(output), '-q']
    else:
        driver = workdir / 'driver.py'
        driver.write_text(_DSL_DRIVER.format(source=str(source), output=str(output)), encoding='utf-8')
        cmd = ['manim', str(driver), 'Scene_']
    try:
        proc = subprocess.run(cmd, cwd=workdir, env=_env(), capture_output=True, text=True,
                              timeout=timeout, check=False)
    except subprocess.TimeoutExpired:
        raise RuntimeError(f'timed out after {timeout:g} s') from None
    if proc.returncode != 0 or not output.is_file():
        tail = (proc.stderr or proc.stdout or '').strip().splitlines()[-5:]
        raise RuntimeError(f'exit {proc.returncode}: ' + ' | '.join(tail))
    return output


def sha256_file(path: Path) -> str:
    return 'sha256:' + hashlib.sha256(path.read_bytes()).hexdigest()


def hash_corpus(root: Path, *, keep: Path | None, timeout: float) -> tuple:
    """``({relpath: hash}, {relpath: error})`` for every corpus file."""
    hashes, errors = {}, {}
    files = corpus_files(root)
    for i, source in enumerate(files, 1):
        rel = source.relative_to(root).as_posix()
        print(f'[{i}/{len(files)}] {rel}', flush=True)
        with tempfile.TemporaryDirectory(prefix='animageo-corpus-') as tmp:
            try:
                svg = render(source.resolve(), Path(tmp), timeout)
            except RuntimeError as exc:
                errors[rel] = str(exc)
                print(f'    failed: {exc}', flush=True)
                continue
            hashes[rel] = sha256_file(svg)
            if keep is not None:
                target = keep / (rel + '.svg')
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(svg, target)
    return hashes, errors


def _counts(paths) -> tuple:
    ggb = sum(1 for p in paths if p.endswith('.ggb'))
    return ggb, len(paths) - ggb


def _report_size(paths) -> None:
    ggb, dsl = _counts(paths)
    print(f'corpus: {ggb} .ggb, {dsl} DSL')
    if ggb < MIN_GGB or dsl < MIN_DSL:
        print(f'note: the release check asks for at least {MIN_GGB} .ggb and {MIN_DSL} DSL scenes')


def cmd_record(args) -> int:
    root = Path(args.corpus).resolve()
    hashes, errors = hash_corpus(root, keep=args.keep, timeout=args.timeout)
    if errors:
        for rel, error in sorted(errors.items()):
            print(f'not recorded: {rel}: {error}')
        print(f'{len(errors)} files failed to render; manifest not written')
        return 1
    manifest = {
        'format': FORMAT,
        'animageo': _library_version(),
        'manim': _manim_version(),
        'python': platform.python_version(),
        'files': dict(sorted(hashes.items())),
    }
    path = Path(args.manifest) if args.manifest else root / 'manifest.json'
    path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    _report_size(list(hashes))
    print(f'wrote {path} ({len(hashes)} files)')
    return 0


def cmd_verify(args) -> int:
    root = Path(args.corpus).resolve()
    path = Path(args.manifest) if args.manifest else root / 'manifest.json'
    try:
        manifest = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError) as exc:
        print(f'cannot read {path}: {exc}')
        return 2
    if manifest.get('format') != FORMAT:
        print(f'{path}: not an {FORMAT} manifest')
        return 2
    expected = manifest.get('files', {})
    hashes, errors = hash_corpus(root, keep=args.keep, timeout=args.timeout)
    problems = []
    for rel in sorted(set(expected) | set(hashes) | set(errors)):
        if rel in errors:
            problems.append(f'failed: {rel}: {errors[rel]}')
        elif rel not in expected:
            problems.append(f'not in the manifest: {rel}')
        elif rel not in hashes:
            problems.append(f'missing from the corpus: {rel}')
        elif hashes[rel] != expected[rel]:
            problems.append(f'changed: {rel}')
    for line in problems:
        print(line)
    print(f"recorded with animageo {manifest.get('animageo')}, manim {manifest.get('manim')}; "
          f'now animageo {_library_version()}, manim {_manim_version()}')
    _report_size(list(expected))
    print(f'{len(expected)} files, {len(problems)} differences')
    return 1 if problems else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    sub = parser.add_subparsers(dest='command', required=True)
    for name, func, text in (('record', cmd_record, 'render the corpus and write the manifest'),
                             ('verify', cmd_verify, 'render the corpus and compare with the manifest')):
        p = sub.add_parser(name, help=text)
        p.add_argument('corpus', help='directory with *.ggb and DSL *.py files')
        p.add_argument('-m', '--manifest', help='manifest path (default: <corpus>/manifest.json)')
        p.add_argument('--keep', type=Path, help='keep the rendered SVGs in this directory')
        p.add_argument('--timeout', type=float, default=300.0, help='seconds per file (default 300)')
        p.set_defaults(func=func)
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    if shutil.which('manim') is None:
        print('manim is not installed (the classic renderer needs it)')
        return 2
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
