"""Type stubs for DSL namespace — IDE sees typed factories.

Constructor signatures for ``Point``, ``Line``, ``Circle``, etc.
live on the **classes themselves** in ``proxy.pyi`` (via ``__init__``
overloads). This module re-exports them here so ``from animageo.dsl
import *`` pulls ``Point`` as a class that the IDE treats as
constructible via ``Point(3, 4)``.

Derived commands (``Midpoint``, ``Intersect``, ``Distance``, …) that
aren't bound to a single result type stay as plain function
signatures below.

Regeneration
------------

To refresh this file after adding commands to ``lib_commands.py``::

    python3 -m animageo.parsers.dsl._regen_stubs
"""

from typing import Any, Callable, Optional, Sequence, Tuple, TypeVar, Union

_E = TypeVar('_E', bound='ElementProxy')

# Re-export the per-type classes — they serve as both types AND
# constructors (``class Point: def __init__(x, y) -> None``).
from .proxy import (
    Angle,
    Arc,
    Boolean,
    Circle,
    CircleSector,
    Conic,
    ElementProxy,
    Function,
    ImplicitCurve,
    Line,
    LocusCurve,
    Measure,
    Point,
    Polygon,
    Ray,
    Segment,
    Vector,
)


# ── Extra GGB constructors (not unique shapes — alias to existing) ──

def CircleArc(*args: Any, name: Optional[str] = ...) -> Arc: ...
def CircularArc(*args: Any, name: Optional[str] = ...) -> Arc: ...
def CircumcircleArc(*args: Any, name: Optional[str] = ...) -> Arc: ...
def CircumcircularArc(*args: Any, name: Optional[str] = ...) -> Arc: ...
def CircularSector(*args: Any, name: Optional[str] = ...) -> CircleSector: ...
def CircumcircleSector(*args: Any, name: Optional[str] = ...) -> CircleSector: ...
def CircumcircularSector(*args: Any, name: Optional[str] = ...) -> CircleSector: ...
def Semicircle(*args: Any, name: Optional[str] = ...) -> Arc: ...
def Ellipse(*args: Any, name: Optional[str] = ...) -> Conic: ...
def Hyperbola(*args: Any, name: Optional[str] = ...) -> Conic: ...
def Parabola(*args: Any, name: Optional[str] = ...) -> Conic: ...
def Incircle(*args: Any, name: Optional[str] = ...) -> Circle: ...
def Locus(*args: Any, name: Optional[str] = ...) -> LocusCurve: ...


# ── Point-producing commands ─────────────────────────────────────

def Midpoint(*args: Any, name: Optional[str] = ...) -> Point: ...
def Center(obj: Union[Circle, Conic], *, name: Optional[str] = ...) -> Point: ...
def Centroid(*points: Point, name: Optional[str] = ...) -> Point: ...
def Vertex(obj: Union[Polygon, Conic], *, name: Optional[str] = ...) -> Point: ...
def Focus(conic: Conic, *, name: Optional[str] = ...) -> Point: ...
def Trilinear(a: Point, b: Point, c: Point, x: float, y: float, z: float, *, name: Optional[str] = ...) -> Point: ...
def ClosestPoint(path: Union[Line, Segment, Ray, Circle], point: Point, *, name: Optional[str] = ...) -> Point: ...


# ── Line-producing commands ──────────────────────────────────────

def AngularBisector(*args: Any, name: Optional[str] = ...) -> Line: ...
def LineBisector(*args: Any, name: Optional[str] = ...) -> Line: ...
def OrthogonalLine(*args: Any, name: Optional[str] = ...) -> Line: ...
def PerpendicularBisector(*args: Any, name: Optional[str] = ...) -> Line: ...
def PerpendicularLine(*args: Any, name: Optional[str] = ...) -> Line: ...
def Tangent(*args: Any, name: Optional[str] = ...) -> Line: ...
def Polar(a: Union[Point, Line], conic: Conic, *, name: Optional[str] = ...) -> Union[Line, Point]: ...
def Directrix(conic: Conic, *, name: Optional[str] = ...) -> Line: ...
def Axes(conic: Conic, *, name: Optional[str] = ..., _outputs: int = ...) -> Tuple[Line, Line]: ...
def MajorAxis(conic: Conic, *, name: Optional[str] = ...) -> Line: ...
def MinorAxis(conic: Conic, *, name: Optional[str] = ...) -> Line: ...


# ── Vector-producing commands ────────────────────────────────────

def Direction(obj: Union[Line, Segment, Ray, Vector], *, name: Optional[str] = ...) -> Vector: ...
def UnitVector(obj: Union[Line, Segment, Ray, Vector], *, name: Optional[str] = ...) -> Vector: ...
def PerpendicularVector(obj: Union[Line, Segment, Vector], *, name: Optional[str] = ...) -> Vector: ...
def UnitPerpendicularVector(obj: Union[Line, Segment, Ray, Vector], *, name: Optional[str] = ...) -> Vector: ...


# ── Measure-producing commands ───────────────────────────────────

def Slope(line: Line, *, name: Optional[str] = ...) -> Measure: ...
def Dot(u: Vector, v: Vector, *, name: Optional[str] = ...) -> Measure: ...
def Cross(u: Vector, v: Vector, *, name: Optional[str] = ...) -> Measure: ...
def AffineRatio(a: Point, b: Point, c: Point, *, name: Optional[str] = ...) -> Measure: ...
def CrossRatio(a: Point, b: Point, c: Point, d: Point, *, name: Optional[str] = ...) -> Measure: ...
def Distance(a: ElementProxy, b: ElementProxy, *, name: Optional[str] = ...) -> Measure: ...
def Radius(circle: Circle, *, name: Optional[str] = ...) -> Measure: ...
def Area(*args: Any, name: Optional[str] = ...) -> Measure: ...
def Length(*args: Any, name: Optional[str] = ...) -> Measure: ...
def Perimeter(*args: Any, name: Optional[str] = ...) -> Measure: ...
def Circumference(*args: Any, name: Optional[str] = ...) -> Measure: ...
def Eccentricity(conic: Conic, *, name: Optional[str] = ...) -> Measure: ...
def LinearEccentricity(conic: Conic, *, name: Optional[str] = ...) -> Measure: ...
def SemiMajorAxisLength(conic: Conic, *, name: Optional[str] = ...) -> Measure: ...
def SemiMinorAxisLength(conic: Conic, *, name: Optional[str] = ...) -> Measure: ...
def Value(obj: ElementProxy, *, name: Optional[str] = ...) -> Measure: ...
def Coefficients(obj: ElementProxy, *, name: Optional[str] = ...) -> Any: ...


# ── Boolean tests ────────────────────────────────────────────────

def AreCollinear(*points: Point, name: Optional[str] = ...) -> Boolean: ...
def AreParallel(a: Line, b: Line, *, name: Optional[str] = ...) -> Boolean: ...
def ArePerpendicular(a: Line, b: Line, *, name: Optional[str] = ...) -> Boolean: ...
def AreComplementary(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def AreConcurrent(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def AreConcyclic(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def AreCongruent(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def AreEqual(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def ContainedBy(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def Equality(a: ElementProxy, b: ElementProxy, *, name: Optional[str] = ...) -> Boolean: ...
def Touches(*args: Any, name: Optional[str] = ...) -> Boolean: ...
def Prove(*args: Any, name: Optional[str] = ...) -> Boolean: ...


# ── Intersections (may be multi-output) ──────────────────────────

def Intersect(
    a: ElementProxy,
    b: ElementProxy,
    index: Optional[int] = ...,
    *,
    name: Optional[str] = ...,
    _outputs: int = ...,
) -> Union[Point, Tuple[Point, ...]]: ...


# ── Transforms (preserve input type via TypeVar) ─────────────────

def Rotate(
    obj: _E,
    angle_rad: float,
    center: Optional[Point] = ...,
    *,
    name: Optional[str] = ...,
) -> _E: ...

def Translate(
    obj: _E,
    vec: Union[Vector, Sequence[float]],
    *,
    name: Optional[str] = ...,
) -> _E: ...

def Mirror(
    obj: _E,
    mirror: Union[Point, Line, Circle],
    *,
    name: Optional[str] = ...,
) -> _E: ...

def Reflect(
    obj: _E,
    mirror: Union[Point, Line, Circle],
    *,
    name: Optional[str] = ...,
) -> _E: ...

def Dilate(
    obj: _E,
    factor: Union[float, Measure],
    center: Optional[Point] = ...,
    *,
    name: Optional[str] = ...,
) -> _E: ...

def IsogonalConjugation(*args: Any, name: Optional[str] = ...) -> Point: ...


# ── Arithmetic (binary ops as commands — used internally) ────────

def Add(a: Any, b: Any, *, name: Optional[str] = ...) -> Any: ...
def Sub(a: Any, b: Any, *, name: Optional[str] = ...) -> Any: ...
def Mult(a: Any, b: Any, *, name: Optional[str] = ...) -> Any: ...
def Div(a: Any, b: Any, *, name: Optional[str] = ...) -> Any: ...
def Pow(a: Any, b: Any, *, name: Optional[str] = ...) -> Any: ...
def USub(a: Any, *, name: Optional[str] = ...) -> Any: ...
def Assign(value: Any, *, name: Optional[str] = ...) -> Any: ...

def Abs(x: Any, *, name: Optional[str] = ...) -> Any: ...
def Sqrt(x: Any, *, name: Optional[str] = ...) -> Any: ...
def Sin(x: Any, *, name: Optional[str] = ...) -> Any: ...
def Cos(x: Any, *, name: Optional[str] = ...) -> Any: ...
def Tan(x: Any, *, name: Optional[str] = ...) -> Any: ...
def Ctan(x: Any, *, name: Optional[str] = ...) -> Any: ...
def CpxTo(*args: Any, name: Optional[str] = ...) -> Any: ...

def AngleSize(*args: Any, name: Optional[str] = ...) -> Any: ...


# ── Stylistic helpers ────────────────────────────────────────────

def style(*elements: ElementProxy, **kwargs: Any) -> None: ...
def hide(*elements: ElementProxy) -> None: ...
def show(*elements: ElementProxy) -> None: ...


# ── Math re-exports ──────────────────────────────────────────────

import math
pi: float
e: float
inf: float
nan: float
TYPE_CHECKING: bool

def sqrt(x: float) -> float: ...
def sin(x: float) -> float: ...
def cos(x: float) -> float: ...
def tan(x: float) -> float: ...
def asin(x: float) -> float: ...
def acos(x: float) -> float: ...
def atan(x: float) -> float: ...
def atan2(y: float, x: float) -> float: ...
def exp(x: float) -> float: ...
def log(x: float, base: float = ...) -> float: ...
def floor(x: float) -> int: ...
def ceil(x: float) -> int: ...


# ── Public utility ───────────────────────────────────────────────

class FactoryDict(dict):
    def __missing__(self, key: str) -> Any: ...

def build_namespace(constr: Any) -> FactoryDict: ...

SAFE_BUILTINS: dict


# ── Catch-all for any name we didn't explicitly declare above ────

def __getattr__(name: str) -> Any: ...
