"""Auto-generate ``<basename>_stubs.pyi`` from a loaded ``Construction``.

Invoked by :meth:`AnimaGeoScene.loadGGB` (via ``generate_stubs=True``,
default). Produces a PEP-561 stub file next to the source ``.ggb``
with type declarations for every loaded element, so DSL files can::

    from scene10_stubs import *

and get IDE autocomplete for all names from the GGB without writing
``R: PointProxy`` by hand.

The stub is purely an IDE aid — at runtime, ``dsl.transform`` drops
all imports, and names resolve via ``FactoryDict.__missing__`` against
the active ``Construction``.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...geo.construction import Construction

logger = logging.getLogger(__name__)


def _proxy_type_for(data) -> str:
    """Return the proxy-type name for a geometric data instance.

    Order matters — check subclasses before base classes (Segment
    before Line, Arc before Circle, etc.).
    """
    # Lazy import to avoid cycles at package load.
    from ...geo.lib_elements import (
        Angle, Arc, Circle, CircleSector, Line, Point, Polygon, Ray,
        Segment, Vector,
    )
    from ...geo.lib_vars import AngleSize, Boolean, Measure
    from ...geo.lib_conic import Conic
    from ...geo.lib_function import Function
    from ...geo.lib_implicit import ImplicitCurve

    mapping = [
        (Point, 'Point'),
        (Segment, 'Segment'),           # before Line
        (Ray, 'Ray'),                   # before Line
        (Line, 'Line'),
        (Arc, 'Arc'),                   # before Circle
        (CircleSector, 'CircleSector'), # before Circle
        (Circle, 'Circle'),
        (Angle, 'Angle'),
        (Polygon, 'Polygon'),
        (Vector, 'Vector'),
        (Conic, 'Conic'),
        (Function, 'Function'),
        (ImplicitCurve, 'ImplicitCurve'),
        (Measure, 'Measure'),
        (AngleSize, 'Measure'),         # no dedicated stub class
        (Boolean, 'Boolean'),
    ]
    for cls, proxy in mapping:
        if isinstance(data, cls):
            return proxy
    return 'ElementProxy'


def _is_usable_name(name: str) -> bool:
    """Skip phantoms and non-identifier names."""
    if not name:
        return False
    if name.startswith('_'):
        return False
    if not name.isidentifier():
        return False
    return True


def write_ggb_stubs(constr, ggb_path: str | Path) -> Path | None:
    """Write ``<ggb_basename>_stubs.pyi`` with type stubs for every element.

    Returns the path to the stub file, or ``None`` if writing failed
    (e.g. permission denied). Logs a warning on failure but never
    raises — stubs are a nice-to-have, not a correctness requirement.
    """
    ggb = Path(ggb_path)
    stub_path = ggb.with_name(ggb.stem + '_stubs.pyi')

    # Group names by proxy type for readable output.
    by_type: dict[str, list[str]] = {}
    for elem in constr.elements:
        if not _is_usable_name(elem.name):
            continue
        if elem.data is None:
            # Unbuilt element — skip; we don't know its type.
            continue
        proxy = _proxy_type_for(elem.data)
        by_type.setdefault(proxy, []).append(elem.name)
    for var in constr.vars:
        if not _is_usable_name(var.name):
            continue
        if var.data is None:
            continue
        proxy = _proxy_type_for(var.data)
        by_type.setdefault(proxy, []).append(var.name)

    # Compose the stub file.
    lines: list[str] = [
        f'"""Auto-generated IDE stubs for {ggb.name}.',
        '',
        'Do not edit — regenerated by loadGGB on each call.',
        f'Source: {ggb.name}',
        '"""',
        '',
        'from animageo.dsl import *  # noqa: F401,F403',
        '',
    ]

    for proxy in sorted(by_type):
        names = sorted(by_type[proxy])
        lines.append(f'# ── {proxy} ──')
        for n in names:
            lines.append(f'{n}: {proxy}')
        lines.append('')

    try:
        stub_path.write_text('\n'.join(lines), encoding='utf-8')
        logger.debug("Wrote DSL stubs: %s (%d names)", stub_path,
                     sum(len(v) for v in by_type.values()))
        return stub_path
    except OSError as e:
        logger.warning("Could not write %s: %s", stub_path, e)
        return None
