"""TikZ document assembly: number formatting, colour interning, wrapping.

``TikZDocument`` accumulates body lines and the ``\\definecolor`` declarations
they reference, then renders either a bare ``tikzpicture`` snippet or a full
``standalone`` document.
"""
from __future__ import annotations

import math
from typing import Dict, List, Optional

from .options import TikZOptions


DEFAULT_STANDALONE_PREAMBLE = r"""\documentclass[tikz]{standalone}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english,russian]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usetikzlibrary{arrows.meta}"""


def fmt_num(value: float, precision: int) -> str:
    """Format a float with fixed precision, stripping trailing zeros.

    Collapses ``-0`` to ``0`` and rounds sub-threshold magnitudes to ``0`` so
    the output never carries floating-point noise (``1.0000000001``).
    """
    if value is None or (isinstance(value, float) and (math.isnan(value) or math.isinf(value))):
        return "0"
    v = float(value)
    if abs(v) < 0.5 * 10 ** (-precision):
        return "0"
    s = f"{v:.{precision}f}".rstrip("0").rstrip(".")
    if s in ("-0", ""):
        return "0"
    return s


def hex_of(color) -> str:
    """Return an uppercase 6-digit hex string (no ``#``) for any colour input.

    Imports :class:`manim.ManimColor` lazily so the document/number layer is
    usable (and unit-testable) without manim installed.
    """
    if color is None:
        color = "#000000"
    try:
        from manim import ManimColor
        h = ManimColor(color).to_hex()
    except Exception:
        h = str(color) if isinstance(color, str) and color.startswith("#") else "#000000"
    return h.lstrip("#").upper()[:6].ljust(6, "0")


class TikZDocument:
    """Builder for a TikZ snippet / standalone document."""

    def __init__(self, options: TikZOptions, picture_options: str = ""):
        self.opt = options
        self.picture_options = picture_options
        self._body: List[str] = []
        self._colors: Dict[str, str] = {}   # hex -> macro name
        self._color_order: List[str] = []    # hex in first-seen order

    # ── colours ────────────────────────────────────────────────────────
    def color(self, color) -> str:
        """Intern a colour and return its TikZ macro name (``agc0`` …)."""
        h = hex_of(color)
        name = self._colors.get(h)
        if name is None:
            name = f"agc{len(self._color_order)}"
            self._colors[h] = name
            self._color_order.append(h)
        return name

    # ── body ───────────────────────────────────────────────────────────
    def line(self, text: str) -> None:
        self._body.append(text)

    def comment(self, text: str) -> None:
        self._body.append(f"% {text}")

    def blank(self) -> None:
        self._body.append("")

    # ── coordinate / size helpers ────────────────────────────────────────
    def coord(self, x: float, y: float) -> str:
        p = self.opt.coordinate_precision
        return f"({fmt_num(x, p)},{fmt_num(y, p)})"

    def num(self, value: float) -> str:
        return fmt_num(value, self.opt.coordinate_precision)

    def pt(self, value_pt: float) -> str:
        return f"{fmt_num(value_pt, self.opt.size_precision)}pt"

    # ── rendering ────────────────────────────────────────────────────────
    def _color_defs(self) -> List[str]:
        return [
            f"\\definecolor{{{self._colors[h]}}}{{HTML}}{{{h}}}"
            for h in self._color_order
        ]

    def picture(self) -> str:
        """Render just the ``\\definecolor`` block + ``tikzpicture``."""
        ind = self.opt.indent
        lines: List[str] = []
        if self.opt.comment_header:
            lines.append("% Generated by AnimaGeo — TikZ export")
        lines.extend(self._color_defs())
        opts = f"[{self.picture_options}]" if self.picture_options else ""
        lines.append(f"\\begin{{tikzpicture}}{opts}")
        for b in self._body:
            lines.append(f"{ind}{b}" if b else "")
        lines.append("\\end{tikzpicture}")
        return "\n".join(lines)

    def render(self) -> str:
        """Render the full output per ``options.standalone``."""
        if not self.opt.standalone:
            return self.picture() + "\n"
        preamble = self.opt.standalone_preamble or DEFAULT_STANDALONE_PREAMBLE
        return (
            preamble
            + "\n\\begin{document}\n"
            + self.picture()
            + "\n\\end{document}\n"
        )
